//! C11 backend. Consumes [`crate::ir`] only.
//!
//! The IR is already in the shape C wants — basic blocks, explicit memory, no
//! unwinding — so this file is a transliteration, not a compiler. Anything that
//! required a decision (error ABI, layout, abort points) was decided in
//! lowering; the only thing decided here is C syntax.
//!
//! Two rules keep the output honest under `-O3`:
//!
//! - Wrapping arithmetic is emitted through unsigned types. Signed overflow is
//!   undefined behaviour in C, and `+ - *` are defined to wrap in Ax, so every
//!   signed add/sub/mul/neg round-trips through the matching unsigned type.
//! - Division, remainder, and shifts go through runtime helpers, because the C
//!   edge cases (`INT_MIN / -1`, shift count >= width) are undefined where Ax
//!   defines them.
//!
//! Layout note: this backend uses C struct members and `sizeof`, never the byte
//! offsets computed during lowering. The Cranelift backend uses the offsets.
//! Layout is not observable in v1 (no struct FFI), so the two need not agree —
//! but neither may ever mix the two schemes.

use crate::ir::*;
use std::fmt::Write as _;

pub fn emit(p: &Program) -> Result<String, String> {
    let mut e = Emit {
        p,
        out: String::with_capacity(16 * 1024),
        slot_of: std::collections::HashMap::new(),
        elem_of: std::collections::HashMap::new(),
        defs: std::collections::HashMap::new(),
        skip_emit: std::collections::HashSet::new(),
    };
    e.program()?;
    Ok(e.out)
}

struct Emit<'a> {
    p: &'a Program,
    out: String,
    /// Slot index of a `vN` that is `&sK` for a scalar slot. Load/store
    /// through it becomes `sK` so clang can keep the local in a register.
    slot_of: std::collections::HashMap<ValId, u32>,
    /// Dest of `ElemPtr` → (elem, base, idx). A later load/store becomes `p[i]`.
    elem_of: std::collections::HashMap<ValId, (Repr, ValId, ValId)>,
    /// Last defining op of each SSA value in this function, for peepholes.
    defs: std::collections::HashMap<ValId, Op>,
    /// Values that are computed only to feed a later peephole (e.g. `s +=`).
    skip_emit: std::collections::HashSet<ValId>,
}

/// C type name for a machine type.
fn cty(t: IrTy) -> &'static str {
    match t {
        IrTy::Unit => "AxUnit",
        IrTy::Bool => "bool",
        IrTy::I8 => "int8_t",
        IrTy::I16 => "int16_t",
        IrTy::I32 => "int32_t",
        IrTy::I64 => "int64_t",
        IrTy::U8 => "uint8_t",
        IrTy::U16 => "uint16_t",
        IrTy::U32 => "uint32_t",
        IrTy::U64 => "uint64_t",
        IrTy::F32 => "float",
        IrTy::F64 => "double",
        IrTy::Ptr => "void *",
    }
}

/// Unsigned counterpart, for wrapping arithmetic.
fn uty(t: IrTy) -> &'static str {
    match t {
        IrTy::I8 | IrTy::U8 => "uint8_t",
        IrTy::I16 | IrTy::U16 => "uint16_t",
        IrTy::I32 | IrTy::U32 => "uint32_t",
        IrTy::I64 | IrTy::U64 => "uint64_t",
        other => cty(other),
    }
}

fn agg_name(id: TypeId) -> String {
    format!("AxT{id}")
}

fn res_name(f: &Func) -> String {
    format!("AxR_{}", f.name)
}

fn suffix(t: IrTy) -> &'static str {
    t.name()
}

impl<'a> Emit<'a> {
    fn program(&mut self) -> Result<(), String> {
        self.out.push_str("/* generated by ax — do not edit */\n");
        self.out.push_str("#include \"axrt.h\"\n");
        // Only for rendering results and test names; the language ABI itself
        // lives entirely in axrt.
        self.out.push_str("#include <stdio.h>\n");
        // For `offsetof` in layout descriptors.
        self.out.push_str("#include <stddef.h>\n");
        // Direct `memcmp` for `xs.eq(ys)` (see CallExt ax_rt_mem_eq).
        self.out.push_str("#include <string.h>\n\n");
        self.aggs();
        self.strings();
        self.descriptors();
        self.result_types();
        self.protos();
        self.renderers();
        for f in &self.p.funcs {
            self.func(f)?;
        }
        self.entry();
        Ok(())
    }

    /// Aggregates in definition order. Lowering assigns ids bottom-up, so a
    /// struct's members are always already defined.
    fn aggs(&mut self) {
        for (i, a) in self.p.aggs.iter().enumerate() {
            let id = i as TypeId;
            let n = agg_name(id);
            match &a.kind {
                AggKind::Record => {
                    let _ = writeln!(self.out, "typedef struct {n} {{");
                    if a.fields.is_empty() {
                        // C forbids an empty struct; keep one byte so `sizeof`
                        // and address-of still behave.
                        let _ = writeln!(self.out, "    char _empty;");
                    }
                    for f in &a.fields {
                        match f.agg {
                            Some(x) => {
                                let _ = writeln!(self.out, "    {} {};", agg_name(x), f.name);
                            }
                            None => {
                                let _ = writeln!(self.out, "    {} {};", cty(f.ty), f.name);
                            }
                        }
                    }
                    let _ = writeln!(self.out, "}} {n};  /* {} */\n", a.name);
                }
                AggKind::Variant { cases } => {
                    let _ = writeln!(self.out, "typedef struct {n} {{");
                    let _ = writeln!(self.out, "    int32_t tag;");
                    let has_payload = cases.iter().any(|c| !c.fields.is_empty());
                    if has_payload {
                        let _ = writeln!(self.out, "    union {{");
                        for c in cases {
                            if c.fields.is_empty() {
                                continue;
                            }
                            let _ = writeln!(self.out, "        struct {{");
                            for fi in &c.fields {
                                let f = a.field(*fi);
                                match f.agg {
                                    Some(x) => {
                                        let _ = writeln!(
                                            self.out,
                                            "            {} {};",
                                            agg_name(x),
                                            f.name
                                        );
                                    }
                                    None => {
                                        let _ = writeln!(
                                            self.out,
                                            "            {} {};",
                                            cty(f.ty),
                                            f.name
                                        );
                                    }
                                }
                            }
                            let _ = writeln!(self.out, "        }} {};", c.name);
                        }
                        let _ = writeln!(self.out, "    }} u;");
                    }
                    let _ = writeln!(self.out, "}} {n};  /* {} */\n", a.name);
                }
            }
        }
    }

    /// Member path for a field index: `tag`, `f`, or `u.Case.f`.
    fn access(&self, agg: TypeId, field: u32) -> String {
        let a = self.p.agg(agg);
        match &a.kind {
            AggKind::Record => a.field(field).name.clone(),
            AggKind::Variant { cases } => {
                if field == VARIANT_TAG_FIELD {
                    return "tag".to_string();
                }
                for c in cases {
                    if c.fields.contains(&field) {
                        return format!("u.{}.{}", c.name, a.field(field).name);
                    }
                }
                a.field(field).name.clone()
            }
        }
    }

    fn strings(&mut self) {
        for (i, s) in self.p.strings.iter().enumerate() {
            let _ = writeln!(self.out, "static const char axs{i}[] = {};", c_string(s));
        }
        if !self.p.strings.is_empty() {
            self.out.push('\n');
        }
    }

    /// Static layout descriptors, for aggregates any function asks about.
    ///
    /// Offsets come from `offsetof`, never from the offsets computed during
    /// lowering: this backend lets C choose padding, so C must be the one to
    /// report where fields live.
    fn descriptors(&mut self) {
        let mut needed: Vec<TypeId> = Vec::new();
        for f in &self.p.funcs {
            for b in &f.blocks {
                for i in &b.insts {
                    if let Op::TypeDescriptor(t) = i.op {
                        if !needed.contains(&t) {
                            needed.push(t);
                        }
                    }
                }
            }
        }
        for t in needed {
            let a = self.p.agg(t);
            let n = agg_name(t);
            let _ = writeln!(self.out, "static const AxFieldDesc axdesc_f{t}[] = {{");
            for f in &a.fields {
                let Some(kind) = field_kind(f) else { continue };
                let _ = writeln!(
                    self.out,
                    "    {{ {}, (uint32_t)offsetof({n}, {}), {kind} }},",
                    c_string(&f.name),
                    f.name
                );
            }
            self.out.push_str("};\n");
            let count = a.fields.iter().filter(|f| field_kind(f).is_some()).count();
            let _ = writeln!(
                self.out,
                "static const AxTypeDesc axdesc{t} = {{ {}, (uint32_t)sizeof({n}), {count}, axdesc_f{t} }};\n",
                c_string(&a.name)
            );
        }
    }

    /// One result struct per fallible function: `{ payload, tag }`. Small enough
    /// to come back in registers, which is the whole point of the two-value
    /// error ABI.
    fn result_types(&mut self) {
        for f in &self.p.funcs {
            if !f.is_fallible() {
                continue;
            }
            let n = res_name(f);
            let payload = if f.ret_agg.is_some() || f.ret == IrTy::Unit {
                "AxUnit".to_string()
            } else {
                cty(f.ret).to_string()
            };
            let _ = writeln!(
                self.out,
                "typedef struct {{ {payload} val; int32_t tag; }} {n};"
            );
        }
        if self.p.funcs.iter().any(|f| f.is_fallible()) {
            self.out.push('\n');
        }
    }

    /// Emit the cache and the wrapper for a memoised function.
    ///
    /// Direct-mapped and fixed-size, so the memory cost is bounded and known at
    /// compile time — an unbounded table would trade a time win for an unbounded
    /// space loss. Thread-local, so two threads never share entries.
    fn memo_wrapper(&mut self, f: &Func) {
        let rt = cty(f.ret);
        let n = &f.name;
        let args: Vec<(ValId, &str)> = f
            .params
            .iter()
            .copied()
            .map(|v| (v, cty(f.ty_of(v))))
            .collect();
        let proto = args
            .iter()
            .map(|(v, t)| format!("{t} v{v}"))
            .collect::<Vec<_>>()
            .join(", ");
        let call = args
            .iter()
            .map(|(v, _)| format!("v{v}"))
            .collect::<Vec<_>>()
            .join(", ");
        // One or two integer keys. Two-argument tree recurrences (binomial
        // coefficients) hash both words; one-argument stays a single mix.
        let hash = match args.as_slice() {
            [(a, _)] => format!("(unsigned long)(v{a})"),
            [(a, _), (b, _)] => {
                format!("((unsigned long)(v{a}) * 0x9e3779b97f4a7c15ul ^ (unsigned long)(v{b}))")
            }
            _ => "(unsigned long)0".into(),
        };
        let key_fields = args
            .iter()
            .enumerate()
            .map(|(i, (_, t))| format!("{t} k{i}; "))
            .collect::<String>();
        let key_eq = args
            .iter()
            .enumerate()
            .map(|(i, (v, _))| format!("axmemo_{n}[i].k{i} == v{v}"))
            .collect::<Vec<_>>()
            .join(" && ");
        let key_store = args
            .iter()
            .enumerate()
            .map(|(i, (v, _))| format!("axmemo_{n}[i].k{i} = v{v}; "))
            .collect::<String>();
        let _ = writeln!(
            self.out,
            "\n/* {n} is pure with a self-recursive tree, so its results are cached. */\n\
             typedef struct {{ {key_fields}{rt} v; unsigned char live; }} AxMemo_{n};\n\
             static _Thread_local AxMemo_{n} axmemo_{n}[1u << 12];\n\
             static {rt} {n}_impl({proto});\n\
             static {rt} {n}({proto}) {{\n\
             \x20   unsigned long i = ({hash}) & ((1u << 12) - 1u);\n\
             \x20   if (axmemo_{n}[i].live && {key_eq}) return axmemo_{n}[i].v;\n\
             \x20   {rt} r = {n}_impl({call});\n\
             \x20   {key_store}axmemo_{n}[i].v = r; axmemo_{n}[i].live = 1;\n\
             \x20   return r;\n\
             }}"
        );
    }

    fn signature(&self, f: &Func) -> String {
        self.signature_named(f, &f.name)
    }

    /// Prototype for the body. A memoised function's body lives under `_impl`.
    fn body_signature(&self, f: &Func) -> String {
        if f.memoize {
            self.signature_named(f, &format!("{}_impl", f.name))
        } else {
            self.signature_named(f, &f.name)
        }
    }

    fn signature_named(&self, f: &Func, name: &str) -> String {
        let ret = if f.is_fallible() {
            res_name(f)
        } else if f.ret_agg.is_some() || f.ret == IrTy::Unit {
            "void".to_string()
        } else {
            cty(f.ret).to_string()
        };
        let mut ps = Vec::new();
        for v in &f.params {
            let t = f.ty_of(*v);
            // Aggregate and reference parameters are addresses. They are
            // `restrict` because Ax forbids aliasing mutable references, so the
            // optimiser may assume what the type system already guarantees.
            if t == IrTy::Ptr {
                ps.push(format!("void *restrict v{v}"));
            } else {
                ps.push(format!("{} v{v}", cty(t)));
            }
        }
        if ps.is_empty() {
            ps.push("void".to_string());
        }
        format!("static {ret} {name}({})", ps.join(", "))
    }

    fn protos(&mut self) {
        for f in &self.p.funcs {
            // Memoised functions get their prototypes from the wrapper block.
            if !f.memoize {
                let _ = writeln!(self.out, "{};", self.signature(f));
            }
        }
        self.out.push('\n');
    }

    fn func(&mut self, f: &Func) -> Result<(), String> {
        // A memoised function is emitted as the body under `_impl` plus a
        // wrapper that owns the cache. Recursive calls go through the wrapper,
        // which is the whole point: the recursion is what hits the cache.
        if f.memoize {
            self.memo_wrapper(f);
        }
        self.slot_of.clear();
        self.elem_of.clear();
        self.defs.clear();
        self.skip_emit = unused_ssa(f);
        let sig = self.body_signature(f);
        let _ = writeln!(self.out, "{sig} {{");

        // Frame slots.
        for (i, s) in f.slots.iter().enumerate() {
            match s.kind {
                Repr::Scalar(t) => {
                    let _ = writeln!(self.out, "    {} s{i};", cty(t));
                }
                Repr::Agg(a) => {
                    let _ = writeln!(self.out, "    {} s{i};", agg_name(a));
                }
            }
        }
        // Region arenas: one per lexical region, released on exit, plus the
        // allocator handle that names it.
        for (i, r) in f.regions.iter().enumerate() {
            let _ = writeln!(self.out, "    AxArena r{i};  /* {} */", r.name);
            let _ = writeln!(self.out, "    AxAlloc ra{i} = {{ AX_ALLOC_ARENA, &r{i} }};");
        }
        // Every SSA value is a local; parameters already are.
        let params: std::collections::HashSet<ValId> = f.params.iter().copied().collect();
        for (v, t) in f.val_tys.iter().enumerate() {
            let v = v as ValId;
            if params.contains(&v) {
                continue;
            }
            let _ = writeln!(self.out, "    {} v{v};", cty(*t));
        }
        if !f.slots.is_empty() || !f.val_tys.is_empty() {
            // Silence "set but not used" for values only fed to dead code.
            self.out.push_str("    (void)0;\n");
        }

        let loops = find_counted_loops(f);
        let whiles = find_while_loops(f, &loops);
        let skip = counted_skip_set(f, &loops);
        let wskip = while_skip_set(f, &whiles);
        let mut i = 0;
        while i < f.blocks.len() {
            let b = &f.blocks[i];
            if skip.contains(&b.id) || wskip.contains(&b.id) {
                i += 1;
                continue;
            }
            let _ = writeln!(self.out, "bb{}: ;", b.id);
            for inst in &b.insts {
                self.inst(f, inst)?;
            }
            if let Some(lp) = jump_into_counted(&b.term, &loops) {
                self.emit_counted_for(f, lp, &loops)?;
            } else if let Some(wp) = jump_into_while(&b.term, &whiles) {
                self.emit_while(f, wp, &loops, &whiles)?;
            } else {
                self.term(f, &b.term)?;
            }
            i += 1;
        }
        self.out.push_str("}\n\n");
        Ok(())
    }

    /// `v_i = lo; for (; v_i < hi; v_i++) { body }` then jump to the exit.
    fn emit_counted_for(
        &mut self,
        f: &Func,
        lp: &CountedLoop,
        loops: &[CountedLoop],
    ) -> Result<(), String> {
        let i = lp.ind;
        let _ = writeln!(self.out, "    v{i} = v{};", lp.lo);
        let _ = writeln!(self.out, "    for (; v{i} < v{}; v{i}++) {{", lp.hi);
        // Body entry first, then the other blocks that stay inside this
        // `for`. Nested counted loops are emitted as nested `for`s from
        // the jump that enters them, not as raw members.
        let mut members = counted_body_blocks(f, lp, loops);
        members.retain(|id| *id != lp.body);
        members.insert(0, lp.body);
        for bid in members {
            if bid != lp.body {
                let _ = writeln!(self.out, "bb{}: ;", bid);
            }
            let b = f.block(bid);
            for inst in &b.insts {
                self.inst(f, inst)?;
            }
            if let Some(inner) = jump_into_counted(&b.term, loops).filter(|n| n.head != lp.head) {
                self.emit_counted_for(f, inner, loops)?;
            } else if bid == lp.body && matches!(&b.term, Term::Jump(e) if e.to == lp.step) {
                // Fall through to the `for` increment. A trailing `continue`
                // is a no-op that still hides the reduction from clang.
            } else {
                self.term_in_loop(f, &b.term, lp)?;
            }
        }
        self.out.push_str("    }\n");
        let _ = writeln!(self.out, "    goto bb{};", lp.exit);
        Ok(())
    }

    /// `while (1) { head; if (!cond) break; body }` then jump to the exit.
    fn emit_while(
        &mut self,
        f: &Func,
        wp: &WhileLoop,
        loops: &[CountedLoop],
        whiles: &[WhileLoop],
    ) -> Result<(), String> {
        self.out.push_str("    while (1) {\n");
        let head = f.block(wp.head);
        for inst in &head.insts {
            self.inst(f, inst)?;
        }
        let _ = writeln!(self.out, "    if (!v{}) break;", wp.cond);
        let mut members = while_body_blocks(f, wp, loops, whiles);
        members.retain(|id| *id != wp.body);
        members.insert(0, wp.body);
        for bid in members {
            if bid != wp.body {
                let _ = writeln!(self.out, "bb{}: ;", bid);
            }
            let b = f.block(bid);
            for inst in &b.insts {
                self.inst(f, inst)?;
            }
            if let Some(inner) = jump_into_counted(&b.term, loops) {
                self.emit_counted_for(f, inner, loops)?;
            } else if let Some(inner) =
                jump_into_while(&b.term, whiles).filter(|n| n.head != wp.head)
            {
                self.emit_while(f, inner, loops, whiles)?;
            } else if bid == wp.body && matches!(&b.term, Term::Jump(e) if e.to == wp.head) {
                // Fall through to the next `while` test.
            } else {
                self.term_in_while(f, &b.term, wp)?;
            }
        }
        self.out.push_str("    }\n");
        let _ = writeln!(self.out, "    goto bb{};", wp.exit);
        Ok(())
    }

    fn term_in_while(&mut self, f: &Func, t: &Term, wp: &WhileLoop) -> Result<(), String> {
        match t {
            Term::Jump(e) if e.to == wp.head => {
                self.out.push_str("    continue;\n");
                Ok(())
            }
            Term::Jump(e) if e.to == wp.exit => {
                self.out.push_str("    break;\n");
                Ok(())
            }
            Term::Br {
                cond,
                then_e,
                else_e,
            } => {
                let _ = writeln!(self.out, "    if (v{cond}) {{");
                self.edge_in_while(f, then_e, wp, "        ");
                self.out.push_str("    } else {\n");
                self.edge_in_while(f, else_e, wp, "        ");
                self.out.push_str("    }\n");
                Ok(())
            }
            other => self.term(f, other),
        }
    }

    fn edge_in_while(&mut self, f: &Func, e: &Edge, wp: &WhileLoop, indent: &str) {
        if e.to == wp.head {
            let _ = writeln!(self.out, "{indent}continue;");
        } else if e.to == wp.exit {
            let _ = writeln!(self.out, "{indent}break;");
        } else {
            self.edge(f, e, indent);
        }
    }

    /// Like [`Self::term`], but a jump to this loop's step is `continue`
    /// and a jump to its exit is `break`, so clang sees a real `for`.
    fn term_in_loop(&mut self, f: &Func, t: &Term, lp: &CountedLoop) -> Result<(), String> {
        match t {
            Term::Jump(e) if e.to == lp.step => {
                self.out.push_str("    continue;\n");
                Ok(())
            }
            Term::Jump(e) if e.to == lp.exit => {
                self.out.push_str("    break;\n");
                Ok(())
            }
            Term::Br {
                cond,
                then_e,
                else_e,
            } => {
                let _ = writeln!(self.out, "    if (v{cond}) {{");
                self.edge_in_loop(f, then_e, lp, "        ");
                self.out.push_str("    } else {\n");
                self.edge_in_loop(f, else_e, lp, "        ");
                self.out.push_str("    }\n");
                Ok(())
            }
            other => self.term(f, other),
        }
    }

    /// `s = s + x` / `s = x + s` → `s += x` so clang sees a reduction.
    fn emit_acc_add(&mut self, f: &Func, slot: u32, val: ValId) -> bool {
        let Some(Op::Bin {
            op: BinKind::Add,
            l,
            r,
        }) = self.defs.get(&val)
        else {
            return false;
        };
        let t = f.ty_of(val);
        if t.is_float() || t == IrTy::Bool {
            return false;
        }
        let (acc, other) = if self.is_slot_load(*l, slot) {
            (*l, *r)
        } else if self.is_slot_load(*r, slot) {
            (*r, *l)
        } else {
            return false;
        };
        let _ = acc;
        let rhs = self.c_expr(f, other);
        let _ = writeln!(self.out, "    s{slot} += {rhs};");
        true
    }

    /// C expression for an SSA value, inlining a load/`p[i]`/bin when cheap.
    fn c_expr(&self, f: &Func, v: ValId) -> String {
        match self.defs.get(&v) {
            Some(Op::Load { ptr, .. }) => {
                if let Some(s) = self.slot_of.get(ptr) {
                    format!("s{s}")
                } else if let Some((elem, base, idx)) = self.elem_of.get(ptr).copied() {
                    index_expr(elem, base, idx)
                } else {
                    format!("v{v}")
                }
            }
            Some(Op::Bin { op, l, r }) => {
                let t = f.ty_of(*l);
                let le = self.c_expr(f, *l);
                let re = self.c_expr(f, *r);
                format!("({})", bin_expr(*op, t, &le, &re))
            }
            Some(Op::ConstInt(n)) => {
                let t = f.ty_of(v);
                format!(
                    "({})({}){}{}",
                    cty(t),
                    uty(t),
                    if *n < 0 { "-" } else { "" },
                    format_args!("{}{}", n.unsigned_abs(), int_suffix(t))
                )
            }
            _ => format!("v{v}"),
        }
    }

    fn is_slot_load(&self, v: ValId, slot: u32) -> bool {
        matches!(
            self.defs.get(&v),
            Some(Op::Load { ptr, .. }) if self.slot_of.get(ptr) == Some(&slot)
        )
    }

    fn edge_in_loop(&mut self, f: &Func, e: &Edge, lp: &CountedLoop, indent: &str) {
        if e.to == lp.step {
            let _ = writeln!(self.out, "{indent}continue;");
        } else if e.to == lp.exit {
            let _ = writeln!(self.out, "{indent}break;");
        } else {
            self.edge(f, e, indent);
        }
    }

    fn inst(&mut self, f: &Func, i: &Inst) -> Result<(), String> {
        let dst = i.result();
        if let Some(v) = dst {
            self.defs.insert(v, i.op.clone());
        }
        // Book-keeping first so a later `s += p[i]*q[i]` can inline even
        // when the ElemPtr / SlotAddr assignment itself is skipped.
        match &i.op {
            Op::ElemPtr { elem, ptr, idx } => {
                if let Some(v) = dst {
                    self.elem_of.insert(v, (*elem, *ptr, *idx));
                }
            }
            Op::SlotAddr(s) => {
                if let Some(v) = dst {
                    if matches!(
                        f.slots.get(*s as usize).map(|si| &si.kind),
                        Some(Repr::Scalar(_))
                    ) {
                        self.slot_of.insert(v, *s);
                    }
                }
            }
            _ => {}
        }
        if let Some(v) = dst {
            if self.skip_emit.contains(&v) {
                return Ok(());
            }
        }
        macro_rules! set {
            ($e:expr) => {{
                let v = dst.ok_or("internal: value-producing op with no result")?;
                let _ = writeln!(self.out, "    v{v} = {};", $e);
            }};
        }
        match &i.op {
            Op::ConstInt(n) => {
                let v = dst.unwrap();
                let t = f.ty_of(v);
                // Write through the unsigned type so a negative literal narrowed
                // to a smaller width is a defined conversion.
                let _ = writeln!(
                    self.out,
                    "    v{v} = ({})({}){}{};",
                    cty(t),
                    uty(t),
                    if *n < 0 { "-" } else { "" },
                    format_args!("{}{}", n.unsigned_abs(), int_suffix(t))
                );
            }
            Op::ConstFloat(x) => set!(format_c_float(*x, f.ty_of(dst.unwrap()))),
            Op::ConstBool(b) => set!(if *b { "true" } else { "false" }),
            Op::ConstUnit => set!("(AxUnit)0"),
            Op::ConstStr(idx) => set!(format!("(void *)axs{idx}")),
            Op::Bin { op, l, r } => {
                let t = f.ty_of(*l);
                set!(self.bin(*op, t, *l, *r));
            }
            Op::Un { op, v } => {
                let t = f.ty_of(*v);
                let s = match op {
                    // Wrapping negation: negate in unsigned, cast back.
                    UnKind::Neg => format!("({})(-({})v{v})", cty(t), uty(t)),
                    UnKind::FNeg => format!("(-v{v})"),
                    UnKind::Not => format!("(!v{v})"),
                    UnKind::BitNot => format!("({})(~({})v{v})", cty(t), uty(t)),
                    UnKind::CanonNaN => {
                        if t == IrTy::F32 {
                            format!("ax_canon_f32(v{v})")
                        } else {
                            format!("ax_canon_f64(v{v})")
                        }
                    }
                };
                set!(s);
            }
            Op::Cast { kind, v } => {
                let to = f.ty_of(dst.unwrap());
                let from = f.ty_of(*v);
                let s = match kind {
                    CastKind::SExt | CastKind::Trunc => {
                        // Narrowing an unsigned value is defined; narrowing a
                        // signed one goes through unsigned to stay defined.
                        format!("({})(({}) ({}) v{v})", cty(to), uty(to), cty(from))
                    }
                    CastKind::ZExt => format!("({})(({}) v{v})", cty(to), uty(from)),
                    CastKind::SToF | CastKind::UToF | CastKind::FCast => {
                        format!("({})v{v}", cty(to))
                    }
                    CastKind::FToS => format!("ax_f2i_{}(v{v})", suffix(to)),
                    CastKind::FToU => format!("ax_f2u_{}(v{v})", suffix(to)),
                    CastKind::Bitcast => format!("({})v{v}", cty(to)),
                };
                set!(s);
            }
            Op::Select { c, a, b } => set!(format!("(v{c} ? v{a} : v{b})")),
            Op::Load { ty, ptr } => {
                if let Some(s) = self.slot_of.get(ptr) {
                    set!(format!("s{s}"));
                } else if let Some((elem, base, idx)) = self.elem_of.get(ptr).copied() {
                    set!(index_expr(elem, base, idx));
                } else {
                    set!(format!("*({} *)v{ptr}", cty(*ty)));
                }
            }
            Op::Store { ty, ptr, val } => {
                if let Some(s) = self.slot_of.get(ptr).copied() {
                    if self.emit_acc_add(f, s, *val) {
                        return Ok(());
                    }
                    let _ = writeln!(self.out, "    s{s} = v{val};");
                } else if let Some((elem, base, idx)) = self.elem_of.get(ptr).copied() {
                    let _ = writeln!(self.out, "    {} = v{val};", index_expr(elem, base, idx));
                } else {
                    let _ = writeln!(self.out, "    *({} *)v{ptr} = v{val};", cty(*ty));
                }
            }
            Op::FieldPtr { agg, field, ptr } => {
                let acc = self.access(*agg, *field);
                set!(format!("(void *)&(({} *)v{ptr})->{acc}", agg_name(*agg)));
            }
            Op::ElemPtr { elem, ptr, idx } => {
                if let Some(v) = dst {
                    self.elem_of.insert(v, (*elem, *ptr, *idx));
                    if !elem_ptr_escapes(f, v) {
                        return Ok(());
                    }
                }
                let s = match elem {
                    Repr::Scalar(t) => format!("(void *)(({} *)v{ptr} + v{idx})", cty(*t)),
                    Repr::Agg(a) => format!("(void *)(({} *)v{ptr} + v{idx})", agg_name(*a)),
                };
                set!(s);
            }
            Op::CopyAgg { ty, dst: d, src } => {
                let n = agg_name(*ty);
                let _ = writeln!(self.out, "    *({n} *)v{d} = *(const {n} *)v{src};");
            }
            Op::SlotAddr(s) => {
                if let Some(v) = dst {
                    if matches!(
                        f.slots.get(*s as usize).map(|si| &si.kind),
                        Some(Repr::Scalar(_))
                    ) {
                        self.slot_of.insert(v, *s);
                    }
                    // Only materialise `&sN` when something other than load/store
                    // uses the pointer. Otherwise clang sees an address-taken
                    // accumulator and will not vectorise the reduction.
                    if slot_addr_escapes(f, v) {
                        set!(format!("(void *)&s{s}"));
                    }
                } else {
                    set!(format!("(void *)&s{s}"));
                }
            }
            Op::FuncAddr(fid) => set!(format!("(void *)&{}", self.p.func(*fid).name)),
            Op::RegionEnter(r) => {
                let _ = writeln!(self.out, "    ax_arena_init(&r{r});");
            }
            Op::RegionExit(r) => {
                let _ = writeln!(self.out, "    ax_arena_release(&r{r});");
            }
            Op::RegionAllocHandle(r) => {
                // One handle per region, initialised next to its arena.
                set!(format!("(void *)&ra{r}"));
            }
            Op::TypeDescriptor(t) => set!(format!("(void *)&axdesc{t}")),
            Op::SizeOf(r) => {
                let s = match r {
                    Repr::Scalar(t) => format!("sizeof({})", cty(*t)),
                    Repr::Agg(a) => format!("sizeof({})", agg_name(*a)),
                };
                set!(format!("(uint64_t){s}"));
            }
            Op::RegionAlloc {
                region,
                size,
                align,
            } => set!(format!("ax_arena_alloc(&r{region}, v{size}, {align})")),
            Op::UniqueAlloc { size, align } => {
                set!(format!("ax_rt_unique_alloc(v{size}, {align})"))
            }
            Op::UniqueFree(p) => {
                let _ = writeln!(self.out, "    ax_rt_unique_free(v{p});");
            }
            Op::RcAlloc {
                size,
                align,
                atomic,
            } => set!(format!(
                "ax_rt_rc_alloc(v{size}, {align}, {})",
                if *atomic { 1 } else { 0 }
            )),
            Op::RcRetain(p) => {
                let _ = writeln!(self.out, "    ax_rt_rc_retain(v{p});");
            }
            Op::RcRelease(p) => {
                let _ = writeln!(self.out, "    ax_rt_rc_release(v{p});");
            }
            Op::Call { f: callee, args } => {
                let c = self.p.func(*callee);
                let argv: Vec<String> = args.iter().map(|a| format!("v{a}")).collect();
                let call = format!("{}({})", c.name, argv.join(", "));
                if c.is_fallible() {
                    let payload = i.results.first().copied();
                    let tag =
                        i.results.get(1).copied().ok_or(
                            "internal: call to a fallible function must define a tag value",
                        )?;
                    let tmp = format!("_r{tag}");
                    let _ = writeln!(self.out, "    {} {tmp} = {call};", res_name(c));
                    if let Some(pv) = payload {
                        if f.ty_of(pv) != IrTy::Unit {
                            let _ = writeln!(self.out, "    v{pv} = {tmp}.val;");
                        }
                    }
                    let _ = writeln!(self.out, "    v{tag} = {tmp}.tag;");
                } else if c.ret_agg.is_some() || c.ret == IrTy::Unit {
                    let _ = writeln!(self.out, "    {call};");
                } else {
                    set!(call);
                }
            }
            Op::CallExt {
                name,
                args,
                ret,
                fallible: _,
            } => {
                // `eq` is a libc memcmp. Calling through `ax_rt_mem_eq` hid
                // the compare from clang and added a per-call sizeof/wrapper.
                if name == "ax_rt_mem_eq" && args.len() == 3 {
                    set!(format!(
                        "(memcmp(v{}, v{}, (size_t)v{}) == 0)",
                        args[0], args[1], args[2]
                    ));
                    return Ok(());
                }
                let argv: Vec<String> = args.iter().map(|a| format!("v{a}")).collect();
                let call = format!("{name}({})", argv.join(", "));
                if *ret == IrTy::Unit || dst.is_none() {
                    let _ = writeln!(self.out, "    {call};");
                } else {
                    set!(call);
                }
            }
            Op::CallIndirect { ptr, args, ret } => {
                let argv: Vec<String> = args.iter().map(|a| format!("v{a}")).collect();
                let tys: Vec<&str> = args.iter().map(|a| cty(f.ty_of(*a))).collect();
                let fnty = format!("{} (*)({})", cty(*ret), tys.join(", "));
                let call = format!("(({fnty})v{ptr})({})", argv.join(", "));
                if *ret == IrTy::Unit || dst.is_none() {
                    let _ = writeln!(self.out, "    {call};");
                } else {
                    set!(call);
                }
            }
        }
        Ok(())
    }

    fn bin(&self, op: BinKind, t: IrTy, l: ValId, r: ValId) -> String {
        bin_expr(op, t, &format!("v{l}"), &format!("v{r}"))
    }

    /// Block arguments are copied through temporaries: a join whose argument is
    /// another block's parameter would otherwise clobber it mid-assignment.
    fn edge(&mut self, f: &Func, e: &Edge, indent: &str) {
        let target = f.block(e.to);
        for (i, (p, a)) in target.params.iter().zip(&e.args).enumerate() {
            let _ = writeln!(self.out, "{indent}{} _e{i} = v{a};", cty(f.ty_of(*p)));
        }
        for (i, p) in target.params.iter().enumerate() {
            let _ = writeln!(self.out, "{indent}v{p} = _e{i};");
        }
        let _ = writeln!(self.out, "{indent}goto bb{};", e.to);
    }

    fn term(&mut self, f: &Func, t: &Term) -> Result<(), String> {
        match t {
            Term::Jump(e) => {
                self.out.push_str("    {\n");
                self.edge(f, e, "        ");
                self.out.push_str("    }\n");
            }
            Term::Br {
                cond,
                then_e,
                else_e,
            } => {
                let _ = writeln!(self.out, "    if (v{cond}) {{");
                self.edge(f, then_e, "        ");
                self.out.push_str("    } else {\n");
                self.edge(f, else_e, "        ");
                self.out.push_str("    }\n");
            }
            Term::Switch { on, cases, default } => {
                let _ = writeln!(self.out, "    switch (v{on}) {{");
                for (k, e) in cases {
                    let _ = writeln!(self.out, "    case {k}: {{");
                    self.edge(f, e, "        ");
                    self.out.push_str("    }\n");
                }
                self.out.push_str("    default: {\n");
                self.edge(f, default, "        ");
                self.out.push_str("    }\n    }\n");
            }
            Term::Ret(v) => {
                if f.is_fallible() {
                    match v {
                        Some(x) if f.ret_agg.is_none() && f.ret != IrTy::Unit => {
                            let _ = writeln!(
                                self.out,
                                "    return ({}){{ .val = v{x}, .tag = 0 }};",
                                res_name(f)
                            );
                        }
                        _ => {
                            let _ =
                                writeln!(self.out, "    return ({}){{ .tag = 0 }};", res_name(f));
                        }
                    }
                } else if f.ret_agg.is_some() || f.ret == IrTy::Unit {
                    self.out.push_str("    return;\n");
                } else {
                    match v {
                        Some(x) => {
                            let _ = writeln!(self.out, "    return v{x};");
                        }
                        None => {
                            // Falling out of a value-returning function is a
                            // lowering bug, but emit something defined.
                            let _ = writeln!(self.out, "    return ({})0;", cty(f.ret));
                        }
                    }
                }
            }
            Term::RetErr(tag) => {
                if !f.is_fallible() {
                    return Err(format!("@{}: ret.err in an infallible function", f.name));
                }
                let _ = writeln!(self.out, "    return ({}){{ .tag = v{tag} }};", res_name(f));
            }
            Term::Abort(code) => {
                let _ = writeln!(self.out, "    ax_abort({});", c_string(code.message()));
            }
            Term::Unreachable => {
                self.out.push_str("    ax_unreachable();\n");
            }
        }
        Ok(())
    }

    /// Emit renderers that print a value in the oracle interpreter's canonical
    /// form (`9i32`, `{ a: 11i32 }`, `Some { value: 3i32 }`).
    ///
    /// This is what makes differential testing meaningful: without it, a native
    /// run can only be compared through an 8-bit exit status. Every aggregate
    /// reachable from `main`'s return type gets one.
    fn renderers(&mut self) {
        let mut needed = Vec::new();
        if let Some(m) = self.p.main {
            if let Some(a) = self.p.func(m).ret_agg {
                collect_aggs(self.p, a, &mut needed);
            }
        }
        for a in &needed {
            let _ = writeln!(
                self.out,
                "static void ax_render_{a}(const {} *v);",
                agg_name(*a)
            );
        }
        for a in &needed {
            let def = self.p.agg(*a);
            let _ = writeln!(
                self.out,
                "static void ax_render_{a}(const {} *v) {{",
                agg_name(*a)
            );
            match &def.kind {
                AggKind::Record => {
                    if def.name == "str" {
                        self.out.push_str(
                            "    fputc('\"', stdout);\n    fwrite(v->data, 1, (size_t)v->len, stdout);\n    fputc('\"', stdout);\n",
                        );
                    } else {
                        self.out.push_str("    fputs(\"{ \", stdout);\n");
                        for (i, f) in def.fields.iter().enumerate() {
                            if i > 0 {
                                self.out.push_str("    fputs(\", \", stdout);\n");
                            }
                            let _ = writeln!(
                                self.out,
                                "    fputs({}, stdout);",
                                c_string(&format!("{}: ", f.name))
                            );
                            self.render_field(f, "v->");
                        }
                        self.out.push_str("    fputs(\" }\", stdout);\n");
                    }
                }
                AggKind::Variant { cases } => {
                    self.out.push_str("    switch (v->tag) {\n");
                    for c in cases {
                        let _ = writeln!(self.out, "    case {}:", c.tag);
                        let _ = writeln!(self.out, "        fputs({}, stdout);", c_string(&c.name));
                        if !c.fields.is_empty() {
                            self.out.push_str("        fputs(\" { \", stdout);\n");
                            for (i, fi) in c.fields.iter().enumerate() {
                                let f = def.field(*fi);
                                if i > 0 {
                                    self.out.push_str("        fputs(\", \", stdout);\n");
                                }
                                // Payload field names are stored `Case_field`.
                                let bare = f
                                    .name
                                    .strip_prefix(&format!("{}_", c.name))
                                    .unwrap_or(&f.name);
                                let _ = writeln!(
                                    self.out,
                                    "        fputs({}, stdout);",
                                    c_string(&format!("{bare}: "))
                                );
                                self.render_field(f, &format!("v->u.{}.", c.name));
                            }
                            self.out.push_str("        fputs(\" }\", stdout);\n");
                        }
                        self.out.push_str("        break;\n");
                    }
                    self.out
                        .push_str("    default: fputs(\"<bad tag>\", stdout);\n    }\n");
                }
            }
            self.out.push_str("}\n\n");
        }
    }

    fn render_field(&mut self, f: &FieldDef, base: &str) {
        match f.agg {
            Some(inner) => {
                let _ = writeln!(self.out, "    ax_render_{inner}(&{base}{});", f.name);
            }
            None => {
                let _ = writeln!(
                    self.out,
                    "    {}",
                    render_scalar(&format!("{base}{}", f.name), f.ty, &f.src)
                );
            }
        }
    }

    /// C `main`: run the module's `main` if it has one, else the tests.
    fn entry(&mut self) {
        self.out.push_str("int main(int argc, char **argv) {\n");
        self.out.push_str("    ax_rt_init(argc, argv);\n");
        match self.p.main {
            Some(m) => {
                let f = self.p.func(m);
                // `main`'s value is printed in the oracle's canonical form and
                // the process exits 0. Comparing stdout is what the
                // differential tests need; an exit status is only 8 bits.
                let err_arg = if f.is_fallible() {
                    let agg = f.err.as_ref().and_then(|c| c.agg);
                    match agg {
                        Some(a) => {
                            let _ = writeln!(self.out, "    {} _err;", agg_name(a));
                            "&_err"
                        }
                        None => "0",
                    }
                } else {
                    ""
                };
                let ret_slot = f.ret_agg.map(|a| {
                    let _ = writeln!(self.out, "    {} _ret;", agg_name(a));
                    "&_ret"
                });
                let mut argv: Vec<String> = Vec::new();
                if let Some(r) = ret_slot {
                    argv.push(r.to_string());
                }
                if f.is_fallible() {
                    argv.push(err_arg.to_string());
                }
                let call = format!("{}({})", f.name, argv.join(", "));
                if f.is_fallible() {
                    let _ = writeln!(self.out, "    {} _r = {call};", res_name(f));
                    self.out
                        .push_str("    if (_r.tag) { ax_abort(\"uncaught raise from main\"); }\n");
                    if f.ret_agg.is_some() {
                        let _ = writeln!(self.out, "    ax_render_{}(&_ret);", f.ret_agg.unwrap());
                        self.out.push_str("    fputc('\\n', stdout);\n");
                    } else if f.ret != IrTy::Unit {
                        let _ = writeln!(
                            self.out,
                            "    {}",
                            render_scalar("_r.val", f.ret, &f.ret_src)
                        );
                        self.out.push_str("    fputc('\\n', stdout);\n");
                    }
                } else if let Some(a) = f.ret_agg {
                    let _ = writeln!(self.out, "    {call};");
                    let _ = writeln!(self.out, "    ax_render_{a}(&_ret);");
                    self.out.push_str("    fputc('\\n', stdout);\n");
                } else if f.ret == IrTy::Unit {
                    let _ = writeln!(self.out, "    {call};");
                } else {
                    let _ = writeln!(self.out, "    {} _v = {call};", cty(f.ret));
                    let _ = writeln!(self.out, "    {}", render_scalar("_v", f.ret, &f.ret_src));
                    self.out.push_str("    fputc('\\n', stdout);\n");
                }
                self.out.push_str("    ax_rt_shutdown();\n    return 0;\n");
            }
            None => {
                // No `main`: the binary is a test runner, so a build can be
                // executed and differentially compared against the oracle.
                self.out.push_str("    int failed = 0;\n");
                for (name, fid) in &self.p.tests {
                    let f = self.p.func(*fid);
                    let _ = writeln!(
                        self.out,
                        "    if (!{}()) {{ ax_test_failed({}); failed++; }} else {{ ax_test_passed({}); }}",
                        f.name,
                        c_string(name),
                        c_string(name)
                    );
                }
                self.out
                    .push_str("    ax_rt_shutdown();\n    return failed ? 1 : 0;\n");
            }
        }
        self.out.push_str("}\n");
    }
}

fn int_suffix(t: IrTy) -> &'static str {
    match t {
        IrTy::I64 | IrTy::U64 => "ull",
        _ => "u",
    }
}

fn format_c_float(x: f64, t: IrTy) -> String {
    if x.is_nan() {
        return if t == IrTy::F32 {
            "ax_nan_f32()".into()
        } else {
            "ax_nan_f64()".into()
        };
    }
    if x.is_infinite() {
        let s = if x < 0.0 { "-" } else { "" };
        return if t == IrTy::F32 {
            format!("{s}ax_inf_f32()")
        } else {
            format!("{s}ax_inf_f64()")
        };
    }
    // 17 significant digits round-trips an f64 exactly.
    if t == IrTy::F32 {
        format!("{:.9e}f", x)
    } else {
        format!("{:.17e}", x)
    }
}

fn c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for b in s.bytes() {
        match b {
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            b'\n' => out.push_str("\\n"),
            b'\r' => out.push_str("\\r"),
            b'\t' => out.push_str("\\t"),
            0x20..=0x7e => out.push(b as char),
            other => {
                let _ = write!(out, "\\{:03o}", other);
            }
        }
    }
    out.push('"');
    out
}

/// Every aggregate reachable from `root`, dependencies first.
fn collect_aggs(p: &Program, root: TypeId, out: &mut Vec<TypeId>) {
    if out.contains(&root) {
        return;
    }
    let def = p.agg(root);
    for f in &def.fields {
        if let Some(inner) = f.agg {
            collect_aggs(p, inner, out);
        }
    }
    out.push(root);
}

/// Print a scalar exactly as `interp::Value::display` would.
///
/// The suffix comes from the source type (`i32`, `usz`), because the oracle
/// prints `9i32` and machine width alone cannot recover `isz` from `i64`.
fn render_scalar(expr: &str, ty: IrTy, src: &str) -> String {
    match ty {
        IrTy::Bool => format!("fputs({expr} ? \"true\" : \"false\", stdout);"),
        IrTy::Unit => "fputs(\"()\", stdout);".to_string(),
        // Shortest round-trip, so native output matches the oracle exactly.
        IrTy::F32 => format!(
            "{{ char _fb[48]; printf(\"%sf32\", ax_fmt_f32(ax_canon_f32({expr}), _fb, sizeof(_fb))); }}"
        ),
        IrTy::F64 => format!(
            "{{ char _fb[48]; printf(\"%sf64\", ax_fmt_f64(ax_canon_f64({expr}), _fb, sizeof(_fb))); }}"
        ),
        IrTy::Ptr => format!("printf(\"%p\", (void *){expr});"),
        t if t.is_signed() => {
            format!("printf(\"%lld{src}\", (long long){expr});")
        }
        _ => format!("printf(\"%llu{src}\", (unsigned long long){expr});"),
    }
}

/// Runtime field-kind code for a descriptor entry, or `None` for a field the
/// data-driven runtime cannot fill (a nested aggregate other than `str`).
fn field_kind(f: &FieldDef) -> Option<&'static str> {
    if let Some(_) = f.agg {
        // `String` and `&str` are the str aggregate, which the runtime knows.
        return if f.src == "String" || f.src == "str" || f.src.ends_with(" str") {
            Some("AX_FLD_STR")
        } else {
            None
        };
    }
    Some(match f.ty {
        IrTy::I8 => "AX_FLD_I8",
        IrTy::I16 => "AX_FLD_I16",
        IrTy::I32 => "AX_FLD_I32",
        IrTy::I64 => "AX_FLD_I64",
        IrTy::U8 => "AX_FLD_U8",
        IrTy::U16 => "AX_FLD_U16",
        IrTy::U32 => "AX_FLD_U32",
        IrTy::U64 => "AX_FLD_U64",
        IrTy::F32 => "AX_FLD_F32",
        IrTy::F64 => "AX_FLD_F64",
        IrTy::Bool => "AX_FLD_BOOL",
        IrTy::Unit | IrTy::Ptr => return None,
    })
}

/// A counted range-`for` in SSA: head has `i` as its only param, compares
/// `i < hi`, body is one block that jumps to step, step does `i+1` and
/// jumps back to head.
struct CountedLoop {
    head: BlockId,
    body: BlockId,
    step: BlockId,
    exit: BlockId,
    ind: ValId,
    lo: ValId,
    hi: ValId,
}

fn bin_expr(op: BinKind, t: IrTy, l: &str, r: &str) -> String {
    let u = uty(t);
    let c = cty(t);
    match op {
        // Unsigned wrapping is C's native `+ * -`. Extra casts hid the
        // reduction from clang (`s += p[i]*q[i]`).
        BinKind::Add if !t.is_signed() && t != IrTy::Bool => format!("({l} + {r})"),
        BinKind::Sub if !t.is_signed() && t != IrTy::Bool => format!("({l} - {r})"),
        BinKind::Mul if !t.is_signed() && t != IrTy::Bool => format!("({l} * {r})"),
        BinKind::Add => format!("({c})(({u}){l} + ({u}){r})"),
        BinKind::Sub => format!("({c})(({u}){l} - ({u}){r})"),
        BinKind::Mul => format!("({c})(({u}){l} * ({u}){r})"),
        BinKind::DivTrunc => format!("ax_div_{}({l}, {r})", suffix(t)),
        BinKind::RemTrunc => format!("ax_rem_{}({l}, {r})", suffix(t)),
        BinKind::DivTruncNZ if !t.is_signed() => format!("({l} / {r})"),
        BinKind::RemTruncNZ if !t.is_signed() => format!("({l} % {r})"),
        BinKind::DivTruncNZ => format!("ax_div_nz_{}({l}, {r})", suffix(t)),
        BinKind::RemTruncNZ => format!("ax_rem_nz_{}({l}, {r})", suffix(t)),
        BinKind::FAdd => format!("({l} + {r})"),
        BinKind::FSub => format!("({l} - {r})"),
        BinKind::FMul => format!("({l} * {r})"),
        BinKind::FDiv => format!("({l} / {r})"),
        BinKind::FRem => {
            if t == IrTy::F32 {
                format!("ax_fmodf({l}, {r})")
            } else {
                format!("ax_fmod({l}, {r})")
            }
        }
        BinKind::And if t == IrTy::Bool => format!("({l} && {r})"),
        BinKind::Or if t == IrTy::Bool => format!("({l} || {r})"),
        BinKind::And => format!("({c})(({u}){l} & ({u}){r})"),
        BinKind::Or => format!("({c})(({u}){l} | ({u}){r})"),
        BinKind::Xor => format!("({c})(({u}){l} ^ ({u}){r})"),
        BinKind::Shl => format!("ax_shl_{}({l}, {r})", suffix(t)),
        BinKind::Shr => format!("ax_shr_{}({l}, {r})", suffix(t)),
        BinKind::Eq => format!("({l} == {r})"),
        BinKind::Ne => format!("({l} != {r})"),
        BinKind::Lt => format!("({l} < {r})"),
        BinKind::Le => format!("({l} <= {r})"),
        BinKind::Gt => format!("({l} > {r})"),
        BinKind::Ge => format!("({l} >= {r})"),
    }
}

/// SSA values never read after they are defined. Their assignments can be
/// omitted; a later peephole (e.g. `s += p[i]*q[i]`) inlines them.
fn unused_ssa(f: &Func) -> std::collections::HashSet<ValId> {
    let mut defs = std::collections::HashMap::new();
    for b in &f.blocks {
        for inst in &b.insts {
            if let Some(v) = inst.result() {
                defs.insert(v, &inst.op);
            }
        }
    }
    // Results of `s = s + x` are not live; the store becomes `s += x`.
    // Map the dead add → the addend (`x`), so we keep `x`'s tree live.
    let mut dead = std::collections::HashSet::new();
    let mut addend_of = std::collections::HashMap::new();
    for b in &f.blocks {
        for inst in &b.insts {
            if let Op::Store { ptr, val, .. } = &inst.op {
                if let Some(Op::Bin {
                    op: BinKind::Add,
                    l,
                    r,
                }) = defs.get(val)
                {
                    let l_is = matches!(defs.get(l), Some(Op::Load { ptr: p, .. }) if p == ptr);
                    let r_is = matches!(defs.get(r), Some(Op::Load { ptr: p, .. }) if p == ptr);
                    if l_is ^ r_is {
                        dead.insert(*val);
                        addend_of.insert(*val, if l_is { *r } else { *l });
                    }
                }
            }
        }
    }
    // Anything only consumed by a dead value is dead too.
    let mut changed = true;
    while changed {
        changed = false;
        let mut used = std::collections::HashSet::new();
        for b in &f.blocks {
            for inst in &b.insts {
                if inst.result().is_some_and(|v| dead.contains(&v)) {
                    // Inlined as `p[i]` / `s += …` — the array base and
                    // index still appear in the C, so they stay live.
                    // `s += x` still names every value inside `x`.
                    if let Some(x) = inst.result().and_then(|v| addend_of.get(&v)) {
                        // Keep the leaves `c_expr` will name (array bases /
                        // indexes / consts), not the intermediate SSA temps.
                        mark_expr_leaves(*x, &defs, &mut used);
                    } else if let Op::Load { ptr, .. } = &inst.op {
                        if let Some(Op::ElemPtr { ptr: base, idx, .. }) = defs.get(ptr) {
                            used.insert(*base);
                            used.insert(*idx);
                        }
                    } else if let Op::ElemPtr { ptr, idx, .. } = &inst.op {
                        used.insert(*ptr);
                        used.insert(*idx);
                    }
                    continue;
                }
                collect_op_uses(&inst.op, &mut used);
            }
            collect_term_uses(&b.term, &mut used);
        }
        for b in &f.blocks {
            for inst in &b.insts {
                let Some(v) = inst.result() else { continue };
                if dead.contains(&v)
                    || used.contains(&v)
                    || f.params.contains(&v)
                    || b.params.contains(&v)
                {
                    continue;
                }
                if matches!(
                    inst.op,
                    Op::Call { .. }
                        | Op::CallExt { .. }
                        | Op::CallIndirect { .. }
                        | Op::Store { .. }
                        | Op::CopyAgg { .. }
                        | Op::RegionEnter(_)
                        | Op::RegionExit(_)
                        | Op::UniqueFree(_)
                        | Op::RcRetain(_)
                        | Op::RcRelease(_)
                ) {
                    continue;
                }
                dead.insert(v);
                changed = true;
            }
        }
    }
    dead
}

/// Values that appear as C identifiers in an inlined expression: array
/// bases, indexes, constants. Intermediate muls/loads are rebuilt by
/// `c_expr` and must not stay as emitted SSA.
fn mark_expr_leaves<'a>(
    v: ValId,
    defs: &std::collections::HashMap<ValId, &'a Op>,
    used: &mut std::collections::HashSet<ValId>,
) {
    match defs.get(&v) {
        Some(Op::Bin { l, r, .. }) => {
            mark_expr_leaves(*l, defs, used);
            mark_expr_leaves(*r, defs, used);
        }
        Some(Op::Un { v: x, .. } | Op::Cast { v: x, .. }) => {
            // Casts are not inlined by `c_expr` today; keep the SSA value.
            used.insert(v);
            mark_expr_leaves(*x, defs, used);
        }
        Some(Op::Load { ptr, .. }) => {
            if matches!(defs.get(ptr), Some(Op::FieldPtr { .. })) {
                // `xs.at(i).score` is FieldPtr + load; `c_expr` does not
                // inline field loads, so the SSA result must stay.
                used.insert(v);
            }
            mark_expr_leaves(*ptr, defs, used);
        }
        Some(Op::FieldPtr { ptr, .. }) => {
            used.insert(v);
            mark_expr_leaves(*ptr, defs, used);
        }
        Some(Op::ElemPtr { ptr, idx, .. }) => {
            used.insert(*ptr);
            used.insert(*idx);
        }
        Some(Op::Select { c, a, b }) => {
            mark_expr_leaves(*c, defs, used);
            mark_expr_leaves(*a, defs, used);
            mark_expr_leaves(*b, defs, used);
        }
        Some(Op::ConstInt(_) | Op::ConstFloat(_) | Op::ConstBool(_) | Op::ConstUnit) => {}
        _ => {
            used.insert(v);
        }
    }
}

fn collect_op_uses(op: &Op, used: &mut std::collections::HashSet<ValId>) {
    match op {
        Op::Bin { l, r, .. } => {
            used.insert(*l);
            used.insert(*r);
        }
        Op::Un { v, .. } | Op::Cast { v, .. } => {
            used.insert(*v);
        }
        Op::Select { c, a, b } => {
            used.insert(*c);
            used.insert(*a);
            used.insert(*b);
        }
        Op::Load { ptr, .. } => {
            used.insert(*ptr);
        }
        Op::Store { ptr, val, .. } => {
            used.insert(*ptr);
            used.insert(*val);
        }
        Op::FieldPtr { ptr, .. } => {
            used.insert(*ptr);
        }
        Op::ElemPtr { ptr, idx, .. } => {
            used.insert(*ptr);
            used.insert(*idx);
        }
        Op::CopyAgg { dst, src, .. } => {
            used.insert(*dst);
            used.insert(*src);
        }
        Op::Call { args, .. } | Op::CallExt { args, .. } => {
            used.extend(args.iter().copied());
        }
        Op::CallIndirect { ptr, args, .. } => {
            used.insert(*ptr);
            used.extend(args.iter().copied());
        }
        Op::RegionAlloc { size, .. } | Op::UniqueAlloc { size, .. } | Op::RcAlloc { size, .. } => {
            used.insert(*size);
        }
        Op::UniqueFree(p) | Op::RcRetain(p) | Op::RcRelease(p) => {
            used.insert(*p);
        }
        _ => {}
    }
}

fn collect_term_uses(t: &Term, used: &mut std::collections::HashSet<ValId>) {
    match t {
        Term::Jump(e) => used.extend(e.args.iter().copied()),
        Term::Br {
            cond,
            then_e,
            else_e,
        } => {
            used.insert(*cond);
            used.extend(then_e.args.iter().copied());
            used.extend(else_e.args.iter().copied());
        }
        Term::Switch { on, cases, default } => {
            used.insert(*on);
            used.extend(default.args.iter().copied());
            for (_, e) in cases {
                used.extend(e.args.iter().copied());
            }
        }
        Term::Ret(Some(x)) | Term::RetErr(x) => {
            used.insert(*x);
        }
        _ => {}
    }
}

fn index_expr(elem: Repr, base: ValId, idx: ValId) -> String {
    match elem {
        Repr::Scalar(t) => format!("(({} *)v{base})[v{idx}]", cty(t)),
        Repr::Agg(a) => format!("(({} *)v{base})[v{idx}]", agg_name(a)),
    }
}

/// `ElemPtr` only used by load/store can stay as `p[i]`; no temp pointer.
fn elem_ptr_escapes(f: &Func, addr: ValId) -> bool {
    for b in &f.blocks {
        for inst in &b.insts {
            match &inst.op {
                Op::Load { ptr, .. } if *ptr == addr => {}
                Op::Store { ptr, .. } if *ptr == addr => {}
                Op::ElemPtr { .. } if inst.result() == Some(addr) => {}
                other if op_uses(other, addr) => return true,
                _ => {}
            }
        }
        if term_uses(&b.term, addr) {
            return true;
        }
    }
    false
}

/// Does `addr` escape as a pointer, or is it only fed to load/store?
fn slot_addr_escapes(f: &Func, addr: ValId) -> bool {
    for b in &f.blocks {
        for inst in &b.insts {
            match &inst.op {
                Op::Load { ptr, .. } if *ptr == addr => {}
                Op::Store { ptr, .. } if *ptr == addr => {}
                Op::SlotAddr(_) if inst.result() == Some(addr) => {}
                other if op_uses(other, addr) => return true,
                _ => {}
            }
        }
        if term_uses(&b.term, addr) {
            return true;
        }
    }
    false
}

fn op_uses(op: &Op, v: ValId) -> bool {
    match op {
        Op::Bin { l, r, .. } => *l == v || *r == v,
        Op::Un { v: x, .. } | Op::Cast { v: x, .. } => *x == v,
        Op::Select { c, a, b } => *c == v || *a == v || *b == v,
        Op::Load { ptr, .. } => *ptr == v,
        Op::Store { ptr, val, .. } => *ptr == v || *val == v,
        Op::FieldPtr { ptr, .. } => *ptr == v,
        Op::ElemPtr { ptr, idx, .. } => *ptr == v || *idx == v,
        Op::CopyAgg { dst, src, .. } => *dst == v || *src == v,
        Op::Call { args, .. } | Op::CallExt { args, .. } => args.contains(&v),
        Op::CallIndirect { ptr, args, .. } => *ptr == v || args.contains(&v),
        Op::RegionAlloc { size, .. } | Op::UniqueAlloc { size, .. } => *size == v,
        Op::UniqueFree(p) | Op::RcRetain(p) | Op::RcRelease(p) => *p == v,
        Op::RcAlloc { size, .. } => *size == v,
        _ => false,
    }
}

fn term_uses(t: &Term, v: ValId) -> bool {
    match t {
        Term::Jump(e) => e.args.contains(&v),
        Term::Br {
            cond,
            then_e,
            else_e,
        } => *cond == v || then_e.args.contains(&v) || else_e.args.contains(&v),
        Term::Switch { on, cases, default } => {
            *on == v || default.args.contains(&v) || cases.iter().any(|(_, e)| e.args.contains(&v))
        }
        Term::Ret(Some(x)) | Term::RetErr(x) => *x == v,
        _ => false,
    }
}

fn jump_into_counted<'a>(t: &Term, loops: &'a [CountedLoop]) -> Option<&'a CountedLoop> {
    match t {
        Term::Jump(e) => loops.iter().find(|l| l.head == e.to),
        _ => None,
    }
}

fn find_counted_loops(f: &Func) -> Vec<CountedLoop> {
    let mut out = Vec::new();
    for b in &f.blocks {
        let Some(lp) = match_counted_loop(f, b) else {
            continue;
        };
        out.push(lp);
    }
    out
}

fn match_counted_loop(f: &Func, head: &Block) -> Option<CountedLoop> {
    if head.params.len() != 1 {
        return None;
    }
    let ind = head.params[0];
    if f.ty_of(ind) != IrTy::U64 {
        return None;
    }
    // Head: optional compare, then `if i < hi { body } else { exit }`.
    let Term::Br {
        cond,
        then_e,
        else_e,
    } = &head.term
    else {
        return None;
    };
    if !then_e.args.is_empty() || !else_e.args.is_empty() {
        return None;
    }
    let hi = find_lt_rhs(head, *cond, ind)?;
    let body_id = then_e.to;
    let step = find_step_from_body(f, body_id, head.id)?;
    let Term::Jump(back) = &step.term else {
        return None;
    };
    if back.to != head.id || back.args.len() != 1 {
        return None;
    }
    // Step must define `next = i + 1` (or wrap-add of a constant 1).
    if !is_add1(step, back.args[0], ind) {
        return None;
    }
    // The incoming `lo` is whatever the unique predecessor passes. We take
    // it from the first jump we see into `head`; every such jump must pass
    // either `lo` (entry) or `next` (latch). The C `for` uses the entry arg.
    let lo = incoming_lo(f, head.id, back.args[0])?;
    Some(CountedLoop {
        head: head.id,
        body: body_id,
        step: step.id,
        exit: else_e.to,
        ind,
        lo,
        hi,
    })
}

fn find_lt_rhs(head: &Block, cond: ValId, ind: ValId) -> Option<ValId> {
    for inst in &head.insts {
        if inst.result() != Some(cond) {
            continue;
        }
        if let Op::Bin {
            op: BinKind::Lt,
            l,
            r,
        } = inst.op
        {
            if l == ind {
                return Some(r);
            }
        }
    }
    None
}

fn is_add1(step: &Block, next: ValId, ind: ValId) -> bool {
    let mut one = None;
    for inst in &step.insts {
        if let Op::ConstInt(1) = inst.op {
            if let Some(v) = inst.result() {
                one = Some(v);
            }
        }
        if inst.result() == Some(next) {
            if let Op::Bin {
                op: BinKind::Add,
                l,
                r,
            } = inst.op
            {
                return (l == ind && Some(r) == one) || (r == ind && Some(l) == one);
            }
        }
    }
    false
}

/// Walk from `body` until we find the unique block that jumps back to `head`
/// with `i+1`. Every path from `body` must reach that step (or diverge).
fn find_step_from_body<'a>(f: &'a Func, body: BlockId, head: BlockId) -> Option<&'a Block> {
    let mut seen = std::collections::HashSet::new();
    let mut stack = vec![body];
    let mut step = None;
    while let Some(id) = stack.pop() {
        if !seen.insert(id) {
            continue;
        }
        let b = f.block(id);
        match &b.term {
            Term::Jump(e)
                if e.to == head
                    && e.args.len() == 1
                    && is_add1(b, e.args[0], f.block(head).params[0]) =>
            {
                if step.is_some() && step.map(|s: &Block| s.id) != Some(id) {
                    return None;
                }
                step = Some(b);
            }
            Term::Jump(e) => {
                if e.to != head {
                    stack.push(e.to);
                }
            }
            Term::Br { then_e, else_e, .. } => {
                stack.push(then_e.to);
                stack.push(else_e.to);
            }
            Term::Abort(_) | Term::Ret(_) | Term::RetErr(_) | Term::Unreachable => {}
            Term::Switch { cases, default, .. } => {
                for (_, e) in cases {
                    stack.push(e.to);
                }
                stack.push(default.to);
            }
        }
    }
    step
}

fn counted_skip_set(f: &Func, loops: &[CountedLoop]) -> std::collections::HashSet<BlockId> {
    let mut skip = std::collections::HashSet::new();
    for lp in loops {
        skip.insert(lp.head);
        skip.insert(lp.step);
        for id in counted_body_blocks(f, lp, loops) {
            skip.insert(id);
        }
    }
    skip
}

fn counted_body_blocks(f: &Func, lp: &CountedLoop, loops: &[CountedLoop]) -> Vec<BlockId> {
    let mut seen = std::collections::HashSet::new();
    let mut stack = vec![lp.body];
    let mut out = Vec::new();
    while let Some(id) = stack.pop() {
        if id == lp.head || id == lp.step || id == lp.exit {
            continue;
        }
        if let Some(nested) = loops.iter().find(|n| n.head == id && n.head != lp.head) {
            // Resume after the nested `for`; do not flatten its internals.
            stack.push(nested.exit);
            continue;
        }
        if !seen.insert(id) {
            continue;
        }
        out.push(id);
        let b = f.block(id);
        match &b.term {
            Term::Jump(e) => stack.push(e.to),
            Term::Br { then_e, else_e, .. } => {
                stack.push(then_e.to);
                stack.push(else_e.to);
            }
            Term::Switch { cases, default, .. } => {
                for (_, e) in cases {
                    stack.push(e.to);
                }
                stack.push(default.to);
            }
            _ => {}
        }
    }
    out.sort();
    out
}

/// Header-test `while`: head has no params, compares, body eventually
/// jumps back to head with no args.
struct WhileLoop {
    head: BlockId,
    body: BlockId,
    exit: BlockId,
    cond: ValId,
}

fn jump_into_while<'a>(t: &Term, loops: &'a [WhileLoop]) -> Option<&'a WhileLoop> {
    match t {
        Term::Jump(e) => loops.iter().find(|l| l.head == e.to),
        _ => None,
    }
}

fn find_while_loops(f: &Func, counted: &[CountedLoop]) -> Vec<WhileLoop> {
    let counted_heads: std::collections::HashSet<BlockId> =
        counted.iter().map(|l| l.head).collect();
    let mut out = Vec::new();
    for b in &f.blocks {
        if counted_heads.contains(&b.id) {
            continue;
        }
        if let Some(wp) = match_while_loop(f, b) {
            out.push(wp);
        }
    }
    out
}

fn match_while_loop(f: &Func, head: &Block) -> Option<WhileLoop> {
    if !head.params.is_empty() {
        return None;
    }
    let Term::Br {
        cond,
        then_e,
        else_e,
    } = &head.term
    else {
        return None;
    };
    if !then_e.args.is_empty() || !else_e.args.is_empty() {
        return None;
    }
    if !jumps_back_to(f, then_e.to, head.id) {
        return None;
    }
    // A real `while` has one entry from outside and latch edges from the
    // body. A diamond that several blocks jump into is not a while — emitting
    // one ate `map_hist`'s join label.
    let mut ext = 0u32;
    for b in &f.blocks {
        if b.id == head.id {
            continue;
        }
        for e in term_edges(&b.term) {
            if e.to == head.id {
                if reaches(f, then_e.to, b.id, head.id) {
                    continue;
                }
                ext += 1;
            }
        }
    }
    if ext != 1 {
        return None;
    }
    Some(WhileLoop {
        head: head.id,
        body: then_e.to,
        exit: else_e.to,
        cond: *cond,
    })
}

fn term_edges(t: &Term) -> Vec<&Edge> {
    match t {
        Term::Jump(e) => vec![e],
        Term::Br { then_e, else_e, .. } => vec![then_e, else_e],
        Term::Switch { cases, default, .. } => {
            let mut v: Vec<&Edge> = cases.iter().map(|(_, e)| e).collect();
            v.push(default);
            v
        }
        _ => vec![],
    }
}

fn reaches(f: &Func, start: BlockId, target: BlockId, stop: BlockId) -> bool {
    let mut seen = std::collections::HashSet::new();
    let mut stack = vec![start];
    while let Some(id) = stack.pop() {
        if id == stop {
            continue;
        }
        if id == target {
            return true;
        }
        if !seen.insert(id) {
            continue;
        }
        for e in term_edges(&f.block(id).term) {
            stack.push(e.to);
        }
    }
    false
}

fn jumps_back_to(f: &Func, start: BlockId, head: BlockId) -> bool {
    let mut seen = std::collections::HashSet::new();
    let mut stack = vec![start];
    while let Some(id) = stack.pop() {
        if !seen.insert(id) {
            continue;
        }
        let b = f.block(id);
        match &b.term {
            Term::Jump(e) if e.to == head && e.args.is_empty() => return true,
            Term::Jump(e) => {
                if e.to != head {
                    stack.push(e.to);
                }
            }
            Term::Br { then_e, else_e, .. } => {
                stack.push(then_e.to);
                stack.push(else_e.to);
            }
            Term::Switch { cases, default, .. } => {
                for (_, e) in cases {
                    stack.push(e.to);
                }
                stack.push(default.to);
            }
            _ => {}
        }
    }
    false
}

fn while_skip_set(f: &Func, loops: &[WhileLoop]) -> std::collections::HashSet<BlockId> {
    let mut skip = std::collections::HashSet::new();
    for wp in loops {
        skip.insert(wp.head);
        for id in while_body_blocks(f, wp, &[], loops) {
            skip.insert(id);
        }
    }
    skip
}

fn while_body_blocks(
    f: &Func,
    wp: &WhileLoop,
    counted: &[CountedLoop],
    whiles: &[WhileLoop],
) -> Vec<BlockId> {
    let mut seen = std::collections::HashSet::new();
    let mut stack = vec![wp.body];
    let mut out = Vec::new();
    while let Some(id) = stack.pop() {
        if id == wp.head || id == wp.exit {
            continue;
        }
        if let Some(nested) = counted.iter().find(|n| n.head == id) {
            stack.push(nested.exit);
            continue;
        }
        if let Some(nested) = whiles.iter().find(|n| n.head == id && n.head != wp.head) {
            stack.push(nested.exit);
            continue;
        }
        if !seen.insert(id) {
            continue;
        }
        out.push(id);
        let b = f.block(id);
        match &b.term {
            Term::Jump(e) => stack.push(e.to),
            Term::Br { then_e, else_e, .. } => {
                stack.push(then_e.to);
                stack.push(else_e.to);
            }
            Term::Switch { cases, default, .. } => {
                for (_, e) in cases {
                    stack.push(e.to);
                }
                stack.push(default.to);
            }
            _ => {}
        }
    }
    out.sort();
    out
}

fn incoming_lo(f: &Func, head: BlockId, next: ValId) -> Option<ValId> {
    for b in &f.blocks {
        if b.id == head {
            continue;
        }
        let edges: Vec<&Edge> = match &b.term {
            Term::Jump(e) => vec![e],
            Term::Br { then_e, else_e, .. } => vec![then_e, else_e],
            _ => continue,
        };
        for e in edges {
            if e.to == head && e.args.len() == 1 && e.args[0] != next {
                return Some(e.args[0]);
            }
        }
    }
    None
}
