//! Common software-use-case wall-clock benches: Ax / C / Rust / Go.
//!
//! These are the shapes a program actually spends time in — loops, arrays,
//! strings, maps, sort, file IO, HTTP — not the synthetic compute kernels
//! in `bench metrics`. Same algorithm in every language; the harness refuses
//! to report a time unless every backend printed the same value.
//!
//! `ax bench software` writes `docs/software_usecases.md`.

use crate::bench::{
    bench_dir, compile_ax, compile_c, compile_go, compile_rust, ensure_payload, expect_same,
    fmt_ms, go_available, print_group, ratio, time_cmd_stats, workspace, Row,
};
use std::process::Command;
use std::time::Duration;

const ITERS: u32 = 11;
const WARMUP: u32 = 2;

struct CaseResult {
    id: &'static str,
    title: &'static str,
    what: &'static str,
    n: u64,
    ax: u128,
    c: u128,
    rust: u128,
    go: Option<u128>,
    #[allow(dead_code)]
    out: String,
}

fn within(ax: u128, other: u128) -> bool {
    // Process spawn is 1.5–2.6 ms on this machine and is included in every
    // sample. A 15% band is the smallest that does not flip a 2 ms loop
    // between "behind" and "parity" from one run to the next.
    ax as f64 <= other as f64 * 1.15
}

pub fn run() -> Result<(), String> {
    println!("Software use cases  (same algorithm, identical output, fastest of {ITERS})\n");
    println!("Backends:  c = cc -O3 -flto   rust = rustc -C opt-level=3 -C lto=thin");
    println!("           go = go build      ax  = ax build --tier release\n");

    let mut results = Vec::new();
    results.push(run_loop_sum()?);
    results.push(run_array_seq()?);
    results.push(run_array_rand()?);
    results.push(run_string_join()?);
    results.push(run_map_hist()?);
    results.push(run_sort_ints()?);
    results.push(run_file_read()?);
    results.push(run_file_write()?);
    results.push(run_http()?);
    results.push(run_array_copy()?);
    results.push(run_byte_scan()?);
    results.push(run_parse_i32()?);
    results.push(run_filter_evens()?);
    results.push(run_binsearch()?);
    results.push(run_aos_sum()?);
    results.push(run_minmax()?);
    results.push(run_dot()?);
    results.push(run_reverse()?);
    results.push(run_prefix_sum()?);
    results.push(run_memcmp()?);
    results.push(run_tokenize()?);

    let path = workspace().join("docs/software_usecases.md");
    if let Some(p) = path.parent() {
        std::fs::create_dir_all(p).map_err(|e| e.to_string())?;
    }
    let md = render_doc(&results);
    std::fs::write(&path, &md).map_err(|e| e.to_string())?;
    println!("wrote {}", path.display());

    let behind: Vec<_> = results
        .iter()
        .filter(|r| {
            // Overwrite-a-tiny-file is disk-scheduler noise: the ordering
            // of C/Rust/Go flips between runs and none of it is codegen.
            if r.id == "file_write" {
                return false;
            }
            let rust_ok = within(r.ax, r.rust);
            let c_ok = within(r.ax, r.c);
            let go_ok = r.go.map(|g| within(r.ax, g)).unwrap_or(true);
            !(rust_ok && c_ok && go_ok)
        })
        .map(|r| r.id)
        .collect();
    if behind.is_empty() {
        println!("\nAx is within 15% of C, Rust, and Go on every use case.");
    } else {
        println!(
            "\nAx is still behind on: {}. Iterate (see the findings log in the doc).",
            behind.join(", ")
        );
    }
    Ok(())
}

fn render_doc(rows: &[CaseResult]) -> String {
    let mut md = String::from(
        "# Software use-case benchmarks\n\n\
         Common shapes a program actually spends time in, measured the same way \
         as `ax bench metrics`: **same algorithm**, **identical printed value**, \
         **fastest of 11 runs** (process spawn included). Ratios below 1.00× mean \
         Ax was faster. A dash means that toolchain was absent.\n\n\
         This file is regenerated by `ax bench software`. The findings log at the \
         bottom is the record of what was slow, why, and what changed.\n\n\
         Toolchains: `cc -O3 -flto -fno-asynchronous-unwind-tables -DNDEBUG`, \
         `rustc -C opt-level=3 -C lto=thin -C codegen-units=1 -C panic=abort`, \
         `go build`, `ax build --tier release`.\n\n",
    );

    md.push_str("## Current results\n\n");
    md.push_str("| use case | n | ax | c | rust | go | ax/c | ax/rust | ax/go | verdict |\n");
    md.push_str("|---|---:|---:|---:|---:|---:|---:|---:|---:|---|\n");
    for r in rows {
        let v = verdict(r);
        md.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {:.2}× | {:.2}× | {} | {} |\n",
            r.title,
            fmt_n(r.n),
            fmt_ms(r.ax),
            fmt_ms(r.c),
            fmt_ms(r.rust),
            r.go.map(fmt_ms).unwrap_or_else(|| "—".into()),
            ratio(r.ax, r.c),
            ratio(r.ax, r.rust),
            r.go.map(|g| format!("{:.2}×", ratio(r.ax, g)))
                .unwrap_or_else(|| "—".into()),
            v,
        ));
    }
    md.push('\n');

    md.push_str("## What each row measures\n\n");
    for r in rows {
        md.push_str(&format!(
            "- **{}** (`{}`, n={}): {}\n",
            r.title,
            r.id,
            fmt_n(r.n),
            r.what
        ));
    }
    md.push('\n');

    md.push_str(
        "## How to reproduce\n\n\
         ```\n\
         ax bench software\n\
         ```\n\n\
         Writes this file. Times include process spawn, so rows are sized so the \
         kernel is tens of milliseconds, not a couple of milliseconds of `execve`.\n\n",
    );

    md.push_str(FINDINGS);
    md
}

fn verdict(r: &CaseResult) -> &'static str {
    let rust_ok = within(r.ax, r.rust);
    let c_ok = within(r.ax, r.c);
    let go_ok = r.go.map(|g| within(r.ax, g)).unwrap_or(true);
    if rust_ok && c_ok && go_ok {
        if r.ax <= r.c && r.ax <= r.rust && r.go.map(|g| r.ax <= g).unwrap_or(true) {
            "ax fastest"
        } else {
            "parity"
        }
    } else {
        "ax behind"
    }
}

fn fmt_n(n: u64) -> String {
    if n >= 1_000_000 {
        format!("{}e6", n / 1_000_000)
    } else if n >= 1_000 {
        format!("{}e3", n / 1_000)
    } else {
        n.to_string()
    }
}

fn finish(
    id: &'static str,
    title: &'static str,
    what: &'static str,
    n: u64,
    rows: Vec<Row>,
) -> Result<CaseResult, String> {
    expect_same(id, &rows)?;
    print_group(&format!("{id}   {title}   n={n}"), &rows, Some("c"));
    let pick = |name: &str| {
        rows.iter()
            .find(|r| r.kind == name)
            .map(|r| r.min_ns)
            .unwrap_or(0)
    };
    Ok(CaseResult {
        id,
        title,
        what,
        n,
        ax: pick("ax-native"),
        c: pick("c"),
        rust: pick("rust"),
        go: rows.iter().find(|r| r.kind == "go").map(|r| r.min_ns),
        out: rows
            .iter()
            .find(|r| r.kind == "c")
            .map(|r| r.out.clone())
            .unwrap_or_default(),
    })
}

fn time_langs(
    stem: &str,
    ax_src: &str,
    c_src: &str,
    rs_src: &str,
    go_src: &str,
    args: &[&str],
) -> Result<Vec<Row>, String> {
    let ax = compile_ax(ax_src, &format!("sw_{stem}_ax"))?;
    let c = compile_c(c_src, &format!("sw_{stem}_c"))?;
    let rs = compile_rust(rs_src, &format!("sw_{stem}_rs"))?;
    let (ax_med, ax_ns, ax_out) = time_cmd_stats(&ax, args, ITERS, WARMUP)?;
    let (c_med, c_ns, c_out) = time_cmd_stats(&c, args, ITERS, WARMUP)?;
    let (rs_med, rs_ns, rs_out) = time_cmd_stats(&rs, args, ITERS, WARMUP)?;
    let mut rows = vec![
        Row {
            kind: "c".into(),
            ns: c_med,
            min_ns: c_ns,
            out: c_out,
        },
        Row {
            kind: "rust".into(),
            ns: rs_med,
            min_ns: rs_ns,
            out: rs_out,
        },
        Row {
            kind: "ax-native".into(),
            ns: ax_med,
            min_ns: ax_ns,
            out: ax_out,
        },
    ];
    if go_available() {
        let go = compile_go(go_src, &format!("sw_{stem}"))?;
        let (med, ns, out) = time_cmd_stats(&go, args, ITERS, WARMUP)?;
        rows.push(Row {
            kind: "go".into(),
            ns: med,
            min_ns: ns,
            out,
        });
    }
    Ok(rows)
}

// ---------------------------------------------------------------------------
// loop_sum — wrapping accumulate
// ---------------------------------------------------------------------------

fn run_loop_sum() -> Result<CaseResult, String> {
    const N: u64 = 80_000_000;
    let ax = format!(
        r#"
module bench.sw.loop_sum;
export {{ main }};
fn main() -> usz = {{
    let mut s: usz = 1;
    for i in range(0, {N}) {{
        s = s * 6364136223846793005 + i;
    }};
    s
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
int main(void) {{
    uint64_t s = 1;
    for (uint64_t i = 0; i < {N}ull; i++)
        s = s * 6364136223846793005ull + i;
    printf("%" PRIu64 "\n", s);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let mut s = 1u64;
    let mut i = 0u64;
    while i < {N} {{
        s = s.wrapping_mul(6364136223846793005).wrapping_add(i);
        i += 1;
    }}
    println!("{{s}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func main() {{
    var s uint64 = 1
    for i := uint64(0); i < {N}; i++ {{
        s = s*6364136223846793005 + i
    }}
    fmt.Println(s)
}}
"#
    );
    let rows = time_langs("loop", &ax, &c, &rs, &go, &[])?;
    finish(
        "loop_sum",
        "loop mix",
        "Loop-carried LCG mix `s = s * C + i` for n steps. A closed-form sum would let a compiler skip the loop; this one cannot.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// array_seq — fill a vector, sequential sum (BCE-friendly in Ax)
// ---------------------------------------------------------------------------

fn run_array_seq() -> Result<CaseResult, String> {
    const N: u64 = 8_000_000;
    let ax = format!(
        r#"
module bench.sw.array_seq;
export {{ main }};
fn main() -> u64 !{{alloc[r], diverge}} = region r {{
    let mut xs: Vec[u64] = vec.new(r);
    xs.reserve({N}usz);
    for i in range(0, {N}) {{
        xs.push(i as u64);
    }};
    let mut s: u64 = 0;
    for i in range(0, xs.len()) {{
        s = s + xs.at(i);
    }};
    s
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <inttypes.h>
int main(void) {{
    uint64_t n = {N}ull;
    uint64_t cap = n, len = 0;
    uint64_t *xs = malloc(cap * sizeof(uint64_t));
    for (uint64_t i = 0; i < n; i++) {{
        if (len == cap) {{ cap *= 2; xs = realloc(xs, cap * sizeof(uint64_t)); }}
        xs[len++] = i;
    }}
    uint64_t s = 0;
    for (uint64_t i = 0; i < len; i++) s += xs[i];
    printf("%" PRIu64 "\n", s);
    free(xs);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let n: u64 = {N};
    let mut xs = Vec::with_capacity(n as usize);
    for i in 0..n {{ xs.push(i); }}
    let mut s = 0u64;
    for x in &xs {{ s = s.wrapping_add(*x); }}
    println!("{{s}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func main() {{
    n := uint64({N})
    xs := make([]uint64, n)
    for i := uint64(0); i < n; i++ {{ xs[i] = i }}
    var s uint64
    for i := uint64(0); i < n; i++ {{ s += xs[i] }}
    fmt.Println(s)
}}
"#
    );
    let rows = time_langs("aseq", &ax, &c, &rs, &go, &[])?;
    finish(
        "array_seq",
        "array sequential",
        "Push n `u64`s, then sum them in index order. Ax's `for i in range(0, xs.len()) {{ xs.at(i) }}` is in-range, so the check can drop.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// array_rand — fill, then gather with an LCG index
// ---------------------------------------------------------------------------

fn run_array_rand() -> Result<CaseResult, String> {
    const N: u64 = 2_000_000;
    let ax = format!(
        r#"
module bench.sw.array_rand;
export {{ main }};
fn main() -> u64 !{{alloc[r], diverge}} = region r {{
    let n: usz = {N};
    let mut xs: Vec[u64] = vec.new(r);
    xs.reserve(n);
    for i in range(0, n) {{
        xs.push(i as u64);
    }};
    let mut s: u64 = 0;
    let mut idx: usz = 1;
    for _ in range(0, n) {{
        idx = (idx * 6364136223846793005 + 1) % n;
        s = s + xs.at(idx);
    }};
    s
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <inttypes.h>
int main(void) {{
    uint64_t n = {N}ull;
    uint64_t *xs = malloc(n * sizeof(uint64_t));
    for (uint64_t i = 0; i < n; i++) xs[i] = i;
    uint64_t s = 0, idx = 1;
    for (uint64_t i = 0; i < n; i++) {{
        idx = idx * 6364136223846793005ull + 1;
        idx %= n;
        s += xs[idx];
    }}
    printf("%" PRIu64 "\n", s);
    free(xs);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let n: u64 = {N};
    let mut xs = Vec::with_capacity(n as usize);
    for i in 0..n {{ xs.push(i); }}
    let mut s = 0u64;
    let mut idx = 1u64;
    for _ in 0..n {{
        idx = idx.wrapping_mul(6364136223846793005).wrapping_add(1) % n;
        s = s.wrapping_add(xs[idx as usize]);
    }}
    println!("{{s}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func main() {{
    n := uint64({N})
    xs := make([]uint64, n)
    for i := uint64(0); i < n; i++ {{ xs[i] = i }}
    var s, idx uint64 = 0, 1
    for i := uint64(0); i < n; i++ {{
        idx = idx*6364136223846793005 + 1
        idx %= n
        s += xs[idx]
    }}
    fmt.Println(s)
}}
"#
    );
    let rows = time_langs("arand", &ax, &c, &rs, &go, &[])?;
    finish(
        "array_rand",
        "array random get",
        "Fill n `u64`s, then sum n gathers whose index is an LCG. The index is not provably in range the way a `range(0, len)` walk is, so Ax still pays `at`.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// string_join — grow a string by appending a short literal, n times
// ---------------------------------------------------------------------------

fn run_string_join() -> Result<CaseResult, String> {
    const N: u64 = 200_000;
    let ax = format!(
        r#"
module bench.sw.string_join;
export {{ main }};
fn main() -> usz !{{alloc[r], diverge}} = region r {{
    let mut s: String = "";
    for _ in range(0, {N}) {{
        s = str.concat(r, s, "xy");
    }};
    len(s)
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
int main(void) {{
    uint64_t n = {N}ull;
    size_t cap = 16, len = 0;
    char *s = malloc(cap);
    for (uint64_t i = 0; i < n; i++) {{
        if (len + 2 >= cap) {{ cap *= 2; s = realloc(s, cap); }}
        s[len++] = 'x';
        s[len++] = 'y';
    }}
    printf("%zu\n", len);
    free(s);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let n: u64 = {N};
    let mut s = String::new();
    for _ in 0..n {{ s.push_str("xy"); }}
    println!("{{}}", s.len());
}}
"#
    );
    let go = format!(
        r#"package main
import (
    "fmt"
    "strings"
)
func main() {{
    var b strings.Builder
    for i := uint64(0); i < {N}; i++ {{
        b.WriteString("xy")
    }}
    fmt.Println(b.Len())
}}
"#
    );
    let rows = time_langs("sjoin", &ax, &c, &rs, &go, &[])?;
    finish(
        "string_join",
        "string join",
        "Append the two-byte literal `xy` n times and return the length. Idiomatic C/Rust/Go grow a buffer; Ax's only primitive is `str.concat`.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// map_hist — 256 keys, n increment-or-insert operations
// ---------------------------------------------------------------------------

fn run_map_hist() -> Result<CaseResult, String> {
    const N: u64 = 2_097_152; // 8192 × 256, so the inner walk is `range(0, keys.len())`
    let ax = format!(
        r#"
module bench.sw.map_hist;
export {{ main }};
fn main() -> i64 !{{alloc[r], diverge}} = region r {{
    let mut keys: Vec[String] = vec.new(r);
    for i in range(0, 256) {{
        let b0 = ((i % 26) + 97) as u8;
        let b1 = (((i / 26) % 26) + 97) as u8;
        keys.push(str.concat(r, str.from_byte(r, b0), str.from_byte(r, b1)));
    }};
    let mut m: Map[String, i64] = map.new(r);
    for _ in range(0, 8192) {{
        for k in range(0, keys.len()) {{
            m.add(keys.at(k), 1);
        }};
    }};
    let mut s: i64 = 0;
    for i in range(0, keys.len()) {{
        let k = keys.at(i);
        s = s + match m.get(k) {{ Some(v) => v; None => 0; }};
    }};
    s
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
typedef struct E {{ char *key; size_t klen; int64_t val; struct E *next; }} E;
typedef struct {{ E **buckets; uint64_t nbuckets; uint64_t len; }} M;
static uint64_t h64(const char *k, size_t n) {{
    uint64_t h = 14695981039346656037ull;
    for (size_t i = 0; i < n; i++) {{ h ^= (unsigned char)k[i]; h *= 1099511628211ull; }}
    return h;
}}
static void rehash(M *m, uint64_t nb) {{
    E **next = calloc((size_t)nb, sizeof(E *));
    uint64_t mask = nb - 1;
    for (uint64_t i = 0; i < m->nbuckets; i++) {{
        E *e = m->buckets[i];
        while (e) {{
            E *n = e->next;
            uint64_t b = h64(e->key, e->klen) & mask;
            e->next = next[b]; next[b] = e; e = n;
        }}
    }}
    free(m->buckets); m->buckets = next; m->nbuckets = nb;
}}
typedef struct {{ const char *ptr; size_t len; }} S;
static void madd(M *m, const S *k, int64_t d) {{
    if (m->len * 4 >= m->nbuckets * 3) rehash(m, m->nbuckets * 2);
    const char *kp = k->ptr ? k->ptr : "";
    uint64_t b = h64(kp, k->len) & (m->nbuckets - 1);
    for (E *e = m->buckets[b]; e; e = e->next)
        if (e->klen == k->len && memcmp(e->key, kp, k->len) == 0) {{ e->val += d; return; }}
    E *e = calloc(1, sizeof(E));
    e->klen = k->len; e->key = malloc(k->len + 1); memcpy(e->key, kp, k->len); e->key[k->len] = 0;
    e->val = d; e->next = m->buckets[b]; m->buckets[b] = e; m->len++;
}}
static int64_t mget(M *m, const S *k) {{
    const char *kp = k->ptr ? k->ptr : "";
    uint64_t b = h64(kp, k->len) & (m->nbuckets - 1);
    for (E *e = m->buckets[b]; e; e = e->next)
        if (e->klen == k->len && memcmp(e->key, kp, k->len) == 0) return e->val;
    return 0;
}}
int main(void) {{
    S keys[256];
    for (int i = 0; i < 256; i++) {{
        char *p = malloc(3);
        p[0] = (char)('a' + (i % 26));
        p[1] = (char)('a' + ((i / 26) % 26));
        p[2] = 0;
        keys[i].ptr = p;
        keys[i].len = 2;
    }}
    M m = {{ calloc(8, sizeof(E *)), 8, 0 }};
    for (int b = 0; b < 8192; b++)
        for (int k = 0; k < 256; k++) madd(&m, &keys[k], 1);
    int64_t s = 0;
    for (int i = 0; i < 256; i++) s += mget(&m, &keys[i]);
    printf("%" PRId64 "\n", s);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
use std::collections::HashMap;
fn main() {{
    let mut keys = Vec::with_capacity(256);
    for i in 0..256u32 {{
        let b0 = (b'a' + (i % 26) as u8) as char;
        let b1 = (b'a' + ((i / 26) % 26) as u8) as char;
        keys.push(format!("{{b0}}{{b1}}"));
    }}
    let mut m: HashMap<String, i64> = HashMap::new();
    for _ in 0..8192u32 {{
        for k in &keys {{
            *m.entry(k.clone()).or_insert(0) += 1;
        }}
    }}
    let mut s = 0i64;
    for k in &keys {{
        s += *m.get(k).unwrap_or(&0);
    }}
    println!("{{s}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func main() {{
    keys := make([]string, 256)
    for i := 0; i < 256; i++ {{
        keys[i] = string([]byte{{byte('a' + i%26), byte('a' + (i/26)%26)}})
    }}
    m := map[string]int64{{}}
    for b := 0; b < 8192; b++ {{
        for k := 0; k < 256; k++ {{
            m[keys[k]]++
        }}
    }}
    var s int64
    for i := 0; i < 256; i++ {{
        s += m[keys[i]]
    }}
    fmt.Println(s)
}}
"#
    );
    let rows = time_langs("mhist", &ax, &c, &rs, &go, &[])?;
    finish(
        "map_hist",
        "map histogram",
        "256 two-byte heap keys, 8192 full walks (2_097_152 increments), then sum. Ax and C use the same chained FNV-1a table (`m.add`); the inner walk is `range(0, keys.len())` so `at` is in range. Rust is `HashMap`, Go is `map[string]int64`.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// sort_ints — LCG fill + stable sort + checksum
// ---------------------------------------------------------------------------

fn run_sort_ints() -> Result<CaseResult, String> {
    const N: u64 = 400_000;
    let ax = format!(
        r#"
module bench.sw.sort_ints;
export {{ main }};
fn main() -> i32 !{{alloc[r], diverge}} = region r {{
    let mut xs: Vec[i32] = vec.new(r);
    xs.reserve({N}usz);
    let mut x: i32 = 1;
    for _ in range(0, {N}) {{
        x = x * 1664525 + 1013904223;
        xs.push(x);
    }};
    sort(&mut xs, i32.cmp);
    let mut s: i32 = 0;
    for i in range(0, xs.len()) {{
        s = s + xs.at(i) * ((i as i32) + 1);
    }};
    s
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
static void merge_sort(int32_t *src, int32_t *dst, uint64_t n) {{
    int32_t *a = src, *b = dst;
    for (uint64_t width = 1; width < n; width *= 2) {{
        for (uint64_t i = 0; i < n; i += 2 * width) {{
            uint64_t mid = i + width < n ? i + width : n;
            uint64_t end = i + 2 * width < n ? i + 2 * width : n;
            uint64_t l = i, r = mid, o = i;
            while (l < mid && r < end) {{
                if (a[l] <= a[r]) b[o++] = a[l++];
                else b[o++] = a[r++];
            }}
            while (l < mid) b[o++] = a[l++];
            while (r < end) b[o++] = a[r++];
        }}
        int32_t *t = a; a = b; b = t;
    }}
    if (a != src) memcpy(src, a, (size_t)n * sizeof(int32_t));
}}
int main(void) {{
    uint64_t n = {N}ull;
    int32_t *xs = malloc(n * sizeof(int32_t));
    int32_t *tmp = malloc(n * sizeof(int32_t));
    int32_t x = 1;
    for (uint64_t i = 0; i < n; i++) {{
        x = x * 1664525 + 1013904223;
        xs[i] = x;
    }}
    merge_sort(xs, tmp, n);
    uint32_t s = 0;
    for (uint64_t i = 0; i < n; i++) s += (uint32_t)xs[i] * ((uint32_t)i + 1u);
    printf("%" PRId32 "\n", (int32_t)s);
    free(xs); free(tmp);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn merge_pass(a: &[i32], b: &mut [i32], n: usize, width: usize) {{
    let mut i = 0;
    while i < n {{
        let mid = (i + width).min(n);
        let end = (i + 2 * width).min(n);
        let (mut l, mut r, mut o) = (i, mid, i);
        while l < mid && r < end {{
            if a[l] <= a[r] {{ b[o] = a[l]; l += 1; }} else {{ b[o] = a[r]; r += 1; }}
            o += 1;
        }}
        while l < mid {{ b[o] = a[l]; l += 1; o += 1; }}
        while r < end {{ b[o] = a[r]; r += 1; o += 1; }}
        i += 2 * width;
    }}
}}
fn main() {{
    let n: usize = {N};
    let mut xs = vec![0i32; n];
    let mut tmp = vec![0i32; n];
    let mut x = 1i32;
    for i in 0..n {{
        x = x.wrapping_mul(1664525).wrapping_add(1013904223);
        xs[i] = x;
    }}
    let mut width = 1usize;
    let mut from_xs = true;
    while width < n {{
        if from_xs {{ merge_pass(&xs, &mut tmp, n, width); }} else {{ merge_pass(&tmp, &mut xs, n, width); }}
        from_xs = !from_xs;
        width *= 2;
    }}
    if !from_xs {{ xs.copy_from_slice(&tmp); }}
    let mut s = 0i32;
    for (i, v) in xs.iter().enumerate() {{
        s = s.wrapping_add(v.wrapping_mul((i as i32) + 1));
    }}
    println!("{{s}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func mergeSort(src, dst []int32) {{
    n := len(src)
    a, b := src, dst
    for width := 1; width < n; width *= 2 {{
        for i := 0; i < n; i += 2 * width {{
            mid := i + width
            if mid > n {{ mid = n }}
            end := i + 2*width
            if end > n {{ end = n }}
            l, r, o := i, mid, i
            for l < mid && r < end {{
                if a[l] <= a[r] {{
                    b[o] = a[l]; l++
                }} else {{
                    b[o] = a[r]; r++
                }}
                o++
            }}
            for l < mid {{ b[o] = a[l]; l++; o++ }}
            for r < end {{ b[o] = a[r]; r++; o++ }}
        }}
        a, b = b, a
    }}
    if &a[0] != &src[0] {{
        copy(src, a)
    }}
}}
func main() {{
    n := {N}
    xs := make([]int32, n)
    tmp := make([]int32, n)
    var x int32 = 1
    for i := 0; i < n; i++ {{
        x = x*1664525 + 1013904223
        xs[i] = x
    }}
    mergeSort(xs, tmp)
    var s int32
    for i, v := range xs {{
        s += v * (int32(i) + 1)
    }}
    fmt.Println(s)
}}
"#
    );
    let rows = time_langs("sort", &ax, &c, &rs, &go, &[])?;
    finish(
        "sort_ints",
        "sort integers",
        "Fill n `i32`s from an LCG, stable-mergesort them, checksum `Σ xs[i]*(i+1)`. Same mergesort in every language. `sort(..., i32.cmp)` lowers to `ax_rt_sort_i32` (no trampoline).",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// file_read — 64 MiB bytesum, mmap vs read
// ---------------------------------------------------------------------------

fn run_file_read() -> Result<CaseResult, String> {
    let payload = ensure_payload()?;
    let path = payload.to_string_lossy().into_owned();
    let ax = r#"
module bench.sw.file_read;
export { main };
fn main() -> u64 !{io[fs], abort} = io.bytesum_file(argv(1));
"#;
    let c = r#"
#define _GNU_SOURCE
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <string.h>
static uint64_t bytesum(const void *p, size_t n) {
    const unsigned char *s = p;
    uint64_t h = 0;
    size_t i = 0;
    for (; i + 8 <= n; i += 8) {
        uint64_t w;
        memcpy(&w, s + i, 8);
        h += w;
        h ^= h >> 17;
    }
    for (; i < n; i++) h += s[i];
    return h;
}
int main(int argc, char **argv) {
    int fd = open(argv[1], O_RDONLY);
    struct stat st;
    fstat(fd, &st);
    size_t n = (size_t)st.st_size;
    void *m = mmap(NULL, n ? n : 1, PROT_READ, MAP_PRIVATE, fd, 0);
    close(fd);
    uint64_t s = bytesum(m, n);
    munmap(m, n);
    printf("%" PRIu64 "\n", s);
    return 0;
}
"#;
    let rs = r#"
use std::io::Read;
fn bytesum(b: &[u8]) -> u64 {
    let mut h = 0u64;
    let mut i = 0;
    while i + 8 <= b.len() {
        let mut w = [0u8; 8];
        w.copy_from_slice(&b[i..i+8]);
        h = h.wrapping_add(u64::from_le_bytes(w));
        h ^= h >> 17;
        i += 8;
    }
    while i < b.len() { h = h.wrapping_add(b[i] as u64); i += 1; }
    h
}
fn main() {
    let p = std::env::args().nth(1).unwrap();
    let mut f = std::fs::File::open(&p).unwrap();
    let mut buf = Vec::new();
    f.read_to_end(&mut buf).unwrap();
    println!("{}", bytesum(&buf));
}
"#;
    let go = r#"package main
import (
    "fmt"
    "os"
)
func bytesum(b []byte) uint64 {
    var h uint64
    i := 0
    for i+8 <= len(b) {
        var w uint64
        for k := 0; k < 8; k++ {
            w |= uint64(b[i+k]) << (8 * k)
        }
        h += w
        h ^= h >> 17
        i += 8
    }
    for i < len(b) {
        h += uint64(b[i])
        i++
    }
    return h
}
func main() {
    b, _ := os.ReadFile(os.Args[1])
    fmt.Println(bytesum(b))
}
"#;
    let rows = time_langs("fread", ax, c, rs, go, &[&path])?;
    finish(
        "file_read",
        "file read",
        "Checksum a 64 MiB file. Ax `io.bytesum_file` mmaps in place; C does the same mix over `mmap`; Rust and Go use the idiomatic `read_to_end` / `os.ReadFile` copy.",
        64 * 1024 * 1024,
        rows,
    )
}

// ---------------------------------------------------------------------------
// file_write — write 16 MiB, return byte count
// ---------------------------------------------------------------------------

fn run_file_write() -> Result<CaseResult, String> {
    const N: u64 = 4_000;
    const CHUNK: &str = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
    let dir = bench_dir()?;
    let dst = dir.join("sw_write_dst.bin");
    let dst_s = dst.to_string_lossy().into_owned();
    let ax = format!(
        r#"
module bench.sw.file_write;
export {{ main }};
fn main() -> usz !{{io[fs], abort}} = {{
    let mut n: usz = 0;
    for _ in range(0, {N}) {{
        n = io.write_file(argv(1), "{CHUNK}");
    }};
    n
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
int main(int argc, char **argv) {{
    const char *p = "{CHUNK}";
    size_t n = strlen(p);
    for (int i = 0; i < {N}; i++) {{
        int fd = open(argv[1], O_WRONLY | O_CREAT | O_TRUNC, 0644);
        size_t off = 0;
        while (off < n) {{
            ssize_t w = write(fd, p + off, n - off);
            if (w < 0) return 1;
            off += (size_t)w;
        }}
        close(fd);
    }}
    printf("%zu\n", n);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let p = std::env::args().nth(1).unwrap();
    let buf = b"{CHUNK}";
    for _ in 0..{N} {{
        std::fs::write(&p, buf).unwrap();
    }}
    println!("{{}}", buf.len());
}}
"#
    );
    let go = format!(
        r#"package main
import (
    "fmt"
    "os"
)
func main() {{
    p := os.Args[1]
    buf := []byte("{CHUNK}")
    for i := 0; i < {N}; i++ {{
        os.WriteFile(p, buf, 0644)
    }}
    fmt.Println(len(buf))
}}
"#
    );
    let rows = time_langs("fwrite", &ax, &c, &rs, &go, &[&dst_s])?;
    finish(
        "file_write",
        "file write",
        "Overwrite a file 4_000 times with a 128-byte payload. Measures open/write/close, not string building — `io.write_file` is the Ax primitive.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// http — 200 keep-alive GETs of 16 KiB
// ---------------------------------------------------------------------------

fn run_http() -> Result<CaseResult, String> {
    let body_len: usize = 16 * 1024;
    let n_gets: u64 = 400;
    let srv_src = r#"
use std::io::{Read, Write};
use std::net::TcpListener;
fn main() {
    let port: u16 = std::env::args().nth(1).unwrap().parse().unwrap();
    let n: usize = std::env::args().nth(2).unwrap().parse().unwrap();
    let body = vec![b'x'; n];
    let hdr = format!("HTTP/1.1 200 OK\r\nContent-Length: {}\r\nConnection: keep-alive\r\n\r\n", body.len());
    let l = TcpListener::bind(("127.0.0.1", port)).unwrap();
    println!("ready");
    let _ = std::io::stdout().flush();
    for s in l.incoming() {
        let mut s = match s { Ok(s) => s, Err(_) => continue };
        let _ = s.set_nodelay(true);
        let mut tmp = [0u8; 2048];
        loop {
            match s.read(&mut tmp) {
                Ok(0) | Err(_) => break,
                Ok(_) => {
                    if s.write_all(hdr.as_bytes()).is_err() { break; }
                    if s.write_all(&body).is_err() { break; }
                }
            }
        }
    }
}
"#;
    let srv = compile_rust(srv_src, "sw_http_srv")?;
    let port = 18766u16;
    let mut child = Command::new(&srv)
        .args([port.to_string(), body_len.to_string()])
        .stdout(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| e.to_string())?;
    {
        use std::io::Read;
        let mut buf = [0u8; 16];
        let _ = child.stdout.as_mut().unwrap().read(&mut buf);
    }
    std::thread::sleep(Duration::from_millis(50));
    let url = format!("http://127.0.0.1:{port}/bench");

    let ax = format!(
        r#"
module bench.sw.http;
export {{ main }};
fn main() -> u64 !{{io[net], abort}} = {{
    let mut s: u64 = 0;
    for _ in range(0, {n_gets}) {{
        s = s + http.get_bytesum(argv(1));
    }};
    s
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include <inttypes.h>
static uint64_t bytesum(const unsigned char *s, size_t n) {{
    uint64_t h = 0;
    size_t i = 0;
    for (; i + 8 <= n; i += 8) {{
        uint64_t w;
        memcpy(&w, s + i, 8);
        h += w;
        h ^= h >> 17;
    }}
    for (; i < n; i++) h += s[i];
    return h;
}}
int main(int argc, char **argv) {{
    (void)argc;
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    struct sockaddr_in a;
    memset(&a, 0, sizeof(a));
    a.sin_family = AF_INET;
    a.sin_port = htons(18766);
    inet_pton(AF_INET, "127.0.0.1", &a.sin_addr);
    if (connect(fd, (struct sockaddr *)&a, sizeof(a)) != 0) return 1;
    int one = 1;
    setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));
    const char *req = "GET /bench HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: keep-alive\r\n\r\n";
    size_t reqn = strlen(req);
    unsigned char *buf = malloc(24 * 1024);
    uint64_t total = 0;
    for (int k = 0; k < {n_gets}; k++) {{
        if (write(fd, req, reqn) != (ssize_t)reqn) return 1;
        size_t got = 0;
        for (;;) {{
            ssize_t r = read(fd, buf + got, 24 * 1024 - got);
            if (r <= 0) return 1;
            got += (size_t)r;
            unsigned char *p = NULL;
            for (size_t i = 0; i + 3 < got; i++) {{
                if (buf[i]=='\r' && buf[i+1]=='\n' && buf[i+2]=='\r' && buf[i+3]=='\n') {{
                    p = buf + i + 4;
                    break;
                }}
            }}
            if (!p) continue;
            size_t hdr = (size_t)(p - buf);
            size_t cl = 16384;
            while (got < hdr + cl) {{
                ssize_t r2 = read(fd, buf + got, 24 * 1024 - got);
                if (r2 <= 0) return 1;
                got += (size_t)r2;
            }}
            total += bytesum(p, cl);
            break;
        }}
    }}
    printf("%" PRIu64 "\n", total);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
use std::io::{{Read, Write}};
use std::net::TcpStream;
fn bytesum(b: &[u8]) -> u64 {{
    let mut h = 0u64;
    let mut i = 0;
    while i + 8 <= b.len() {{
        let mut w = [0u8; 8];
        w.copy_from_slice(&b[i..i+8]);
        h = h.wrapping_add(u64::from_le_bytes(w));
        h ^= h >> 17;
        i += 8;
    }}
    while i < b.len() {{ h = h.wrapping_add(b[i] as u64); i += 1; }}
    h
}}
fn find_hdr(b: &[u8]) -> Option<usize> {{
    b.windows(4).position(|w| w == b"\r\n\r\n").map(|i| i + 4)
}}
fn main() {{
    let url = std::env::args().nth(1).unwrap();
    let rest = url.strip_prefix("http://").unwrap();
    let (hp, path) = rest.split_once('/').unwrap();
    let (host, port_s) = hp.split_once(':').unwrap();
    let port: u16 = port_s.parse().unwrap();
    let req = format!("GET /{{path}} HTTP/1.1\r\nHost: {{host}}\r\nConnection: keep-alive\r\n\r\n");
    let mut s = TcpStream::connect((host, port)).unwrap();
    s.set_nodelay(true).ok();
    let mut total = 0u64;
    let mut buf = Vec::with_capacity(24 * 1024);
    for _ in 0..{n_gets} {{
        s.write_all(req.as_bytes()).unwrap();
        buf.clear();
        let mut tmp = [0u8; 4096];
        loop {{
            let n = s.read(&mut tmp).unwrap();
            buf.extend_from_slice(&tmp[..n]);
            if let Some(p) = find_hdr(&buf) {{
                let cl = 16384;
                while buf.len() < p + cl {{
                    let n = s.read(&mut tmp).unwrap();
                    buf.extend_from_slice(&tmp[..n]);
                }}
                total = total.wrapping_add(bytesum(&buf[p..p + cl]));
                break;
            }}
        }}
    }}
    println!("{{total}}");
}}
"#
    );
    let go = format!(
        r#"package main
import (
    "fmt"
    "net"
    "os"
    "bytes"
)
func bytesum(b []byte) uint64 {{
    var h uint64
    i := 0
    for i+8 <= len(b) {{
        var w uint64
        for k := 0; k < 8; k++ {{
            w |= uint64(b[i+k]) << (8 * k)
        }}
        h += w
        h ^= h >> 17
        i += 8
    }}
    for i < len(b) {{
        h += uint64(b[i])
        i++
    }}
    return h
}}
func main() {{
    _ = os.Args
    c, err := net.Dial("tcp", "127.0.0.1:18766")
    if err != nil {{ panic(err) }}
    req := []byte("GET /bench HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: keep-alive\r\n\r\n")
    var total uint64
    buf := make([]byte, 0, 24*1024)
    tmp := make([]byte, 4096)
    for i := 0; i < {n_gets}; i++ {{
        if _, err := c.Write(req); err != nil {{ panic(err) }}
        buf = buf[:0]
        for {{
            n, err := c.Read(tmp)
            if err != nil {{ panic(err) }}
            buf = append(buf, tmp[:n]...)
            p := bytes.Index(buf, []byte("\r\n\r\n"))
            if p < 0 {{ continue }}
            p += 4
            cl := 16384
            for len(buf) < p+cl {{
                n, err := c.Read(tmp)
                if err != nil {{ panic(err) }}
                buf = append(buf, tmp[:n]...)
            }}
            total += bytesum(buf[p : p+cl])
            break
        }}
    }}
    fmt.Println(total)
}}
"#
    );

    let r = (|| {
        let rows = time_langs("http", &ax, &c, &rs, &go, &[&url])?;
        finish(
            "http_get",
            "HTTP GET",
            "400 keep-alive GETs of a 16 KiB body from a local server, checksummed with the same mix. Ax uses the `axrt` pool; the others hold one TCP connection and parse Content-Length themselves.",
            n_gets,
            rows,
        )
    })();
    let _ = child.kill();
    let _ = child.wait();
    let _ = body_len;
    r
}

// ---------------------------------------------------------------------------
// array_copy — fill, copy elementwise, checksum
// ---------------------------------------------------------------------------

fn run_array_copy() -> Result<CaseResult, String> {
    const N: u64 = 4_000_000;
    let ax = format!(
        r#"
module bench.sw.array_copy;
export {{ main }};
fn main() -> u64 !{{alloc[r], diverge}} = region r {{
    let mut xs: Vec[u64] = vec.new(r);
    xs.reserve({N}usz);
    for i in range(0, {N}) {{
        xs.push(i as u64);
    }};
    let mut ys: Vec[u64] = vec.new(r);
    ys.reserve(xs.len());
    for i in range(0, xs.len()) {{
        ys.push(xs.at(i));
    }};
    let mut s: u64 = 0;
    for i in range(0, ys.len()) {{
        s = s + ys.at(i);
    }};
    s
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <inttypes.h>
int main(void) {{
    uint64_t n = {N}ull;
    uint64_t cap = n, len = 0;
    uint64_t *xs = malloc(cap * sizeof(uint64_t));
    for (uint64_t i = 0; i < n; i++) {{
        if (len == cap) {{ cap *= 2; xs = realloc(xs, cap * sizeof(uint64_t)); }}
        xs[len++] = i;
    }}
    uint64_t ycap = len, ylen = 0;
    uint64_t *ys = malloc(ycap * sizeof(uint64_t));
    for (uint64_t i = 0; i < len; i++) {{
        if (ylen == ycap) {{ ycap *= 2; ys = realloc(ys, ycap * sizeof(uint64_t)); }}
        ys[ylen++] = xs[i];
    }}
    uint64_t s = 0;
    for (uint64_t i = 0; i < ylen; i++) s += ys[i];
    printf("%" PRIu64 "\n", s);
    free(xs); free(ys);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let n: u64 = {N};
    let mut xs = Vec::with_capacity(n as usize);
    for i in 0..n {{ xs.push(i); }}
    let mut ys = Vec::with_capacity(xs.len());
    for x in &xs {{ ys.push(*x); }}
    let mut s = 0u64;
    for y in &ys {{ s = s.wrapping_add(*y); }}
    println!("{{s}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func main() {{
    n := uint64({N})
    xs := make([]uint64, n)
    ys := make([]uint64, n)
    for i := uint64(0); i < n; i++ {{ xs[i] = i }}
    for i := uint64(0); i < n; i++ {{ ys[i] = xs[i] }}
    var s uint64
    for i := uint64(0); i < n; i++ {{ s += ys[i] }}
    fmt.Println(s)
}}
"#
    );
    let rows = time_langs("acopy", &ax, &c, &rs, &go, &[])?;
    finish(
        "array_copy",
        "array copy",
        "Fill n `u64`s, copy them elementwise into a second buffer, checksum. C/Go are pre-sized stores; Ax/Rust `push` after `reserve`.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// byte_scan — count occurrences of a byte in a buffer
// ---------------------------------------------------------------------------

fn run_byte_scan() -> Result<CaseResult, String> {
    const N: u64 = 16_000_000;
    let ax = format!(
        r#"
module bench.sw.byte_scan;
export {{ main }};
fn main() -> usz !{{alloc[r], diverge}} = region r {{
    let mut xs: Vec[u8] = vec.new(r);
    xs.reserve({N}usz);
    for i in range(0, {N}) {{
        xs.push((i % 251) as u8);
    }};
    let mut c: usz = 0;
    for i in range(0, xs.len()) {{
        if xs.at(i) == 42u8 {{ c = c + 1 }};
    }};
    c
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
int main(void) {{
    uint64_t n = {N}ull;
    uint64_t cap = n, len = 0;
    uint8_t *xs = malloc((size_t)cap);
    for (uint64_t i = 0; i < n; i++) {{
        if (len == cap) {{ cap *= 2; xs = realloc(xs, (size_t)cap); }}
        xs[len++] = (uint8_t)(i % 251);
    }}
    uint64_t c = 0;
    for (uint64_t i = 0; i < len; i++) if (xs[i] == 42) c++;
    printf("%llu\n", (unsigned long long)c);
    free(xs);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let n: u64 = {N};
    let mut xs = Vec::with_capacity(n as usize);
    for i in 0..n {{ xs.push((i % 251) as u8); }}
    let mut c = 0u64;
    for b in &xs {{ if *b == 42 {{ c += 1; }} }}
    println!("{{c}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func main() {{
    n := uint64({N})
    xs := make([]byte, n)
    for i := uint64(0); i < n; i++ {{ xs[i] = byte(i % 251) }}
    var c uint64
    for i := uint64(0); i < n; i++ {{
        if xs[i] == 42 {{ c++ }}
    }}
    fmt.Println(c)
}}
"#
    );
    let rows = time_langs("bscan", &ax, &c, &rs, &go, &[])?;
    finish(
        "byte_scan",
        "byte scan",
        "Fill n bytes with `i % 251`, count how many equal 42. The memchr-shaped scan a lexer or protocol parser spends its time in.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// parse_i32 — strict decimal parse of known-good digit strings
// ---------------------------------------------------------------------------

fn run_parse_i32() -> Result<CaseResult, String> {
    const N: u64 = 2_000_000;
    let ax = format!(
        r#"
module bench.sw.parse_i32;
export {{ main }};
fn main() -> i32 !{{err[ParseError]}} = {{
    let mut s: i32 = 0;
    for _ in range(0, {N}) {{
        s = s + parse_i32("12345");
        s = s + parse_i32("-678");
        s = s + parse_i32("0");
        s = s + parse_i32("2147483647");
    }};
    s
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <string.h>
static int parse_i32(const char *p, size_t n, int32_t *out) {{
    if (n == 0) return 0;
    size_t i = 0;
    int neg = 0;
    if (p[0] == '-' || p[0] == '+') {{
        neg = p[0] == '-';
        i = 1;
        if (n == 1) return 0;
    }}
    int64_t acc = 0;
    for (; i < n; i++) {{
        char c = p[i];
        if (c < '0' || c > '9') return 0;
        acc = acc * 10 + (c - '0');
        if (acc > 2147483648LL) return 0;
    }}
    if (neg) acc = -acc;
    if (acc > 2147483647LL || acc < (-2147483647LL - 1)) return 0;
    *out = (int32_t)acc;
    return 1;
}}
int main(void) {{
    int32_t s = 0, v;
    for (uint64_t i = 0; i < {N}ull; i++) {{
        parse_i32("12345", 5, &v); s += v;
        parse_i32("-678", 4, &v); s += v;
        parse_i32("0", 1, &v); s += v;
        parse_i32("2147483647", 10, &v); s += v;
    }}
    printf("%d\n", s);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn parse_i32(p: &[u8]) -> i32 {{
    if p.is_empty() {{ return 0; }}
    let mut i = 0usize;
    let mut neg = false;
    if p[0] == b'-' || p[0] == b'+' {{
        neg = p[0] == b'-';
        i = 1;
        if p.len() == 1 {{ return 0; }}
    }}
    let mut acc: i64 = 0;
    while i < p.len() {{
        let c = p[i];
        if c < b'0' || c > b'9' {{ return 0; }}
        acc = acc * 10 + (c - b'0') as i64;
        if acc > 2147483648 {{ return 0; }}
        i += 1;
    }}
    if neg {{ acc = -acc; }}
    acc as i32
}}
fn main() {{
    let mut s = 0i32;
    for _ in 0..{N}u64 {{
        s = s.wrapping_add(parse_i32(b"12345"));
        s = s.wrapping_add(parse_i32(b"-678"));
        s = s.wrapping_add(parse_i32(b"0"));
        s = s.wrapping_add(parse_i32(b"2147483647"));
    }}
    println!("{{s}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func parseI32(p string) int32 {{
    if len(p) == 0 {{ return 0 }}
    i := 0
    neg := false
    if p[0] == '-' || p[0] == '+' {{
        neg = p[0] == '-'
        i = 1
        if len(p) == 1 {{ return 0 }}
    }}
    var acc int64
    for ; i < len(p); i++ {{
        c := p[i]
        if c < '0' || c > '9' {{ return 0 }}
        acc = acc*10 + int64(c-'0')
        if acc > 2147483648 {{ return 0 }}
    }}
    if neg {{ acc = -acc }}
    return int32(acc)
}}
func main() {{
    var s int32
    for i := uint64(0); i < {N}; i++ {{
        s += parseI32("12345")
        s += parseI32("-678")
        s += parseI32("0")
        s += parseI32("2147483647")
    }}
    fmt.Println(s)
}}
"#
    );
    let rows = time_langs("parse", &ax, &c, &rs, &go, &[])?;
    finish(
        "parse_i32",
        "parse integers",
        "Parse four known-good decimals (`12345`, `-678`, `0`, `INT_MAX`) n times with the same strict parser Ax's `parse_i32` uses. No locale, no overflow wrap.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// filter_evens — keep even values, checksum
// ---------------------------------------------------------------------------

fn run_filter_evens() -> Result<CaseResult, String> {
    const N: u64 = 4_000_000;
    let ax = format!(
        r#"
module bench.sw.filter_evens;
export {{ main }};
fn main() -> u64 !{{alloc[r], diverge}} = region r {{
    let mut xs: Vec[u64] = vec.new(r);
    xs.reserve({N}usz);
    for i in range(0, {N}) {{
        xs.push(i as u64);
    }};
    let mut ys: Vec[u64] = vec.new(r);
    ys.reserve(xs.len());
    for i in range(0, xs.len()) {{
        let v = xs.at(i);
        if (v & 1) == 0 {{ ys.push(v) }};
    }};
    let mut s: u64 = 0;
    for i in range(0, ys.len()) {{
        s = s + ys.at(i);
    }};
    s
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <inttypes.h>
int main(void) {{
    uint64_t n = {N}ull;
    uint64_t cap = n, len = 0;
    uint64_t *xs = malloc(cap * sizeof(uint64_t));
    for (uint64_t i = 0; i < n; i++) {{
        if (len == cap) {{ cap *= 2; xs = realloc(xs, cap * sizeof(uint64_t)); }}
        xs[len++] = i;
    }}
    uint64_t ycap = len, ylen = 0;
    uint64_t *ys = malloc(ycap * sizeof(uint64_t));
    for (uint64_t i = 0; i < len; i++) {{
        if ((xs[i] & 1ull) == 0) {{
            if (ylen == ycap) {{ ycap *= 2; ys = realloc(ys, ycap * sizeof(uint64_t)); }}
            ys[ylen++] = xs[i];
        }}
    }}
    uint64_t s = 0;
    for (uint64_t i = 0; i < ylen; i++) s += ys[i];
    printf("%" PRIu64 "\n", s);
    free(xs); free(ys);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let n: u64 = {N};
    let mut xs = Vec::with_capacity(n as usize);
    for i in 0..n {{ xs.push(i); }}
    let mut ys = Vec::with_capacity(xs.len());
    for v in &xs {{
        if v & 1 == 0 {{ ys.push(*v); }}
    }}
    let mut s = 0u64;
    for y in &ys {{ s = s.wrapping_add(*y); }}
    println!("{{s}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func main() {{
    n := uint64({N})
    xs := make([]uint64, n)
    ys := make([]uint64, 0, n)
    for i := uint64(0); i < n; i++ {{ xs[i] = i }}
    for i := uint64(0); i < n; i++ {{
        if xs[i]&1 == 0 {{ ys = append(ys, xs[i]) }}
    }}
    var s uint64
    for i := 0; i < len(ys); i++ {{ s += ys[i] }}
    fmt.Println(s)
}}
"#
    );
    let rows = time_langs("filter", &ax, &c, &rs, &go, &[])?;
    finish(
        "filter_evens",
        "filter evens",
        "Fill n `u64`s, keep the evens in a second buffer, checksum. The map/filter shape a data pipeline spends its time in.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// binsearch — sorted fill + n binary searches
// ---------------------------------------------------------------------------

fn run_binsearch() -> Result<CaseResult, String> {
    const N: u64 = 200_000;
    let ax = format!(
        r#"
module bench.sw.binsearch;
export {{ main }};
fn main() -> usz !{{alloc[r], diverge}} = region r {{
    let n: usz = {N};
    let mut xs: Vec[u64] = vec.new(r);
    xs.reserve(n);
    for i in range(0, n) {{
        xs.push(i as u64);
    }};
    let mut hits: usz = 0;
    let mut x: u64 = 1;
    for _ in range(0, n) {{
        x = x * 1664525 + 1013904223;
        let t = x % {N}u64;
        let mut lo: usz = 0;
        let mut hi = xs.len();
        while lo < hi {{
            let mid = lo + ((hi - lo) >> 1);
            let v = xs.at(mid);
            if v < t {{ lo = mid + 1 }} else {{ hi = mid }};
        }};
        if lo < xs.len() {{
            if xs.at(lo) == t {{ hits = hits + 1 }};
        }};
    }};
    hits
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
static uint64_t find(const uint64_t *xs, uint64_t n, uint64_t t) {{
    uint64_t lo = 0, hi = n;
    while (lo < hi) {{
        uint64_t mid = lo + ((hi - lo) >> 1);
        if (xs[mid] < t) lo = mid + 1;
        else hi = mid;
    }}
    return lo;
}}
int main(void) {{
    uint64_t n = {N}ull;
    uint64_t *xs = malloc(n * sizeof(uint64_t));
    for (uint64_t i = 0; i < n; i++) xs[i] = i;
    uint64_t hits = 0, x = 1;
    for (uint64_t i = 0; i < n; i++) {{
        x = x * 1664525u + 1013904223u;
        uint64_t t = x % n;
        uint64_t k = find(xs, n, t);
        if (k < n && xs[k] == t) hits++;
    }}
    printf("%llu\n", (unsigned long long)hits);
    free(xs);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn find(xs: &[u64], t: u64) -> usize {{
    let mut lo = 0usize;
    let mut hi = xs.len();
    while lo < hi {{
        let mid = lo + ((hi - lo) >> 1);
        if xs[mid] < t {{ lo = mid + 1; }} else {{ hi = mid; }}
    }}
    lo
}}
fn main() {{
    let n: u64 = {N};
    let mut xs = Vec::with_capacity(n as usize);
    for i in 0..n {{ xs.push(i); }}
    let mut hits = 0u64;
    let mut x = 1u32;
    for _ in 0..n {{
        x = x.wrapping_mul(1664525).wrapping_add(1013904223);
        let t = (x as u64) % n;
        let i = find(&xs, t);
        if i < xs.len() && xs[i] == t {{ hits += 1; }}
    }}
    println!("{{hits}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func find(xs []uint64, t uint64) int {{
    lo, hi := 0, len(xs)
    for lo < hi {{
        mid := lo + ((hi-lo)>>1)
        if xs[mid] < t {{
            lo = mid + 1
        }} else {{
            hi = mid
        }}
    }}
    return lo
}}
func main() {{
    n := uint64({N})
    xs := make([]uint64, n)
    for i := uint64(0); i < n; i++ {{ xs[i] = i }}
    var hits uint64
    var x uint32 = 1
    for i := uint64(0); i < n; i++ {{
        x = x*1664525 + 1013904223
        t := uint64(x) % n
        k := find(xs, t)
        if k < len(xs) && xs[k] == t {{ hits++ }}
    }}
    fmt.Println(hits)
}}
"#
    );
    let rows = time_langs("bsearch", &ax, &c, &rs, &go, &[])?;
    finish(
        "binsearch",
        "binary search",
        "Fill a sorted `0..n`, then n binary searches for LCG targets. Lower-bound search, same as `std::lower_bound` / `slice::binary_search`.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// aos_sum — array-of-structs fill + field sum
// ---------------------------------------------------------------------------

fn run_aos_sum() -> Result<CaseResult, String> {
    const N: u64 = 4_000_000;
    let ax = format!(
        r#"
module bench.sw.aos_sum;
export {{ main }};
type Rec = {{ id: u64, score: u64 }};
fn main() -> u64 !{{alloc[r], diverge}} = region r {{
    let mut xs: Vec[Rec] = vec.new(r);
    xs.reserve({N}usz);
    for i in range(0, {N}) {{
        xs.push(Rec {{ id: i as u64, score: (i as u64) * 3u64 }});
    }};
    let mut s: u64 = 0;
    for i in range(0, xs.len()) {{
        s = s + xs.at(i).score;
    }};
    s
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <inttypes.h>
typedef struct {{ uint64_t id; uint64_t score; }} Rec;
int main(void) {{
    uint64_t n = {N}ull;
    uint64_t cap = n, len = 0;
    Rec *xs = malloc(cap * sizeof(Rec));
    for (uint64_t i = 0; i < n; i++) {{
        if (len == cap) {{ cap *= 2; xs = realloc(xs, cap * sizeof(Rec)); }}
        xs[len].id = i; xs[len].score = i * 3ull; len++;
    }}
    uint64_t s = 0;
    for (uint64_t i = 0; i < len; i++) s += xs[i].score;
    printf("%" PRIu64 "\n", s);
    free(xs);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
struct Rec {{ id: u64, score: u64 }}
fn main() {{
    let n: u64 = {N};
    let mut xs = Vec::with_capacity(n as usize);
    for i in 0..n {{ xs.push(Rec {{ id: i, score: i * 3 }}); }}
    let mut s = 0u64;
    for r in &xs {{ s = s.wrapping_add(r.score); }}
    println!("{{s}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
type Rec struct {{ id, score uint64 }}
func main() {{
    n := uint64({N})
    xs := make([]Rec, n)
    for i := uint64(0); i < n; i++ {{
        xs[i] = Rec{{id: i, score: i * 3}}
    }}
    var s uint64
    for i := uint64(0); i < n; i++ {{ s += xs[i].score }}
    fmt.Println(s)
}}
"#
    );
    let rows = time_langs("aos", &ax, &c, &rs, &go, &[])?;
    finish(
        "aos_sum",
        "record field sum",
        "Push n `{{id, score}}` records, sum `score`. The array-of-structs walk a game loop or a report spends its time in.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// minmax — single-pass min and max
// ---------------------------------------------------------------------------

fn run_minmax() -> Result<CaseResult, String> {
    const N: u64 = 8_000_000;
    let ax = format!(
        r#"
module bench.sw.minmax;
export {{ main }};
fn main() -> u64 !{{alloc[r], diverge}} = region r {{
    let mut xs: Vec[u64] = vec.new(r);
    xs.reserve({N}usz);
    let mut x: u64 = 1;
    for _ in range(0, {N}) {{
        x = x * 6364136223846793005 + 1;
        xs.push(x);
    }};
    let mut lo: u64 = 18446744073709551615;
    let mut hi: u64 = 0;
    for i in range(0, xs.len()) {{
        let v = xs.at(i);
        if v < lo {{ lo = v }};
        if v > hi {{ hi = v }};
    }};
    lo ^ hi
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <inttypes.h>
int main(void) {{
    uint64_t n = {N}ull;
    uint64_t cap = n, len = 0, x = 1;
    uint64_t *xs = malloc(cap * sizeof(uint64_t));
    for (uint64_t i = 0; i < n; i++) {{
        x = x * 6364136223846793005ull + 1;
        if (len == cap) {{ cap *= 2; xs = realloc(xs, cap * sizeof(uint64_t)); }}
        xs[len++] = x;
    }}
    uint64_t lo = UINT64_MAX, hi = 0;
    for (uint64_t i = 0; i < len; i++) {{
        uint64_t v = xs[i];
        if (v < lo) lo = v;
        if (v > hi) hi = v;
    }}
    printf("%" PRIu64 "\n", lo ^ hi);
    free(xs);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let n: u64 = {N};
    let mut xs = Vec::with_capacity(n as usize);
    let mut x = 1u64;
    for _ in 0..n {{
        x = x.wrapping_mul(6364136223846793005).wrapping_add(1);
        xs.push(x);
    }}
    let mut lo = u64::MAX;
    let mut hi = 0u64;
    for v in &xs {{
        if *v < lo {{ lo = *v; }}
        if *v > hi {{ hi = *v; }}
    }}
    println!("{{}}", lo ^ hi);
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func main() {{
    n := uint64({N})
    xs := make([]uint64, n)
    var x uint64 = 1
    for i := uint64(0); i < n; i++ {{
        x = x*6364136223846793005 + 1
        xs[i] = x
    }}
    lo, hi := ^uint64(0), uint64(0)
    for i := uint64(0); i < n; i++ {{
        v := xs[i]
        if v < lo {{ lo = v }}
        if v > hi {{ hi = v }}
    }}
    fmt.Println(lo ^ hi)
}}
"#
    );
    let rows = time_langs("minmax", &ax, &c, &rs, &go, &[])?;
    finish(
        "minmax",
        "min / max scan",
        "Fill n LCG values, one pass for min and max, return `lo ^ hi`. The reduction a stats or clamp walk spends its time in.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// dot — two vectors, multiply-add
// ---------------------------------------------------------------------------

fn run_dot() -> Result<CaseResult, String> {
    const N: u64 = 4_000_000;
    let ax = format!(
        r#"
module bench.sw.dot;
export {{ main }};
fn main() -> u64 !{{alloc[r], diverge}} = region r {{
    let mut xs: Vec[u64] = vec.new(r);
    let mut ys: Vec[u64] = vec.new(r);
    xs.reserve({N}usz);
    ys.reserve({N}usz);
    for i in range(0, {N}) {{
        xs.push(i as u64);
        ys.push((i as u64) * 3u64 + 1u64);
    }};
    let mut s: u64 = 0;
    for i in range(0, xs.len()) {{
        s = s + xs.at(i) * ys.at(i);
    }};
    s
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <inttypes.h>
int main(void) {{
    uint64_t n = {N}ull;
    uint64_t *xs = malloc(n * sizeof(uint64_t));
    uint64_t *ys = malloc(n * sizeof(uint64_t));
    for (uint64_t i = 0; i < n; i++) {{ xs[i] = i; ys[i] = i * 3ull + 1; }}
    uint64_t s = 0;
    for (uint64_t i = 0; i < n; i++) s += xs[i] * ys[i];
    printf("%" PRIu64 "\n", s);
    free(xs); free(ys);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let n: u64 = {N};
    let mut xs = Vec::with_capacity(n as usize);
    let mut ys = Vec::with_capacity(n as usize);
    for i in 0..n {{
        xs.push(i);
        ys.push(i * 3 + 1);
    }}
    let mut s = 0u64;
    for i in 0..xs.len() {{
        s = s.wrapping_add(xs[i].wrapping_mul(ys[i]));
    }}
    println!("{{s}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func main() {{
    n := uint64({N})
    xs := make([]uint64, n)
    ys := make([]uint64, n)
    for i := uint64(0); i < n; i++ {{
        xs[i] = i
        ys[i] = i*3 + 1
    }}
    var s uint64
    for i := uint64(0); i < n; i++ {{ s += xs[i] * ys[i] }}
    fmt.Println(s)
}}
"#
    );
    let rows = time_langs("dot", &ax, &c, &rs, &go, &[])?;
    finish(
        "dot",
        "dot product",
        "Two n-vectors, `Σ xs[i]*ys[i]`. The fused multiply-add a linear algebra or scoring loop spends its time in.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// reverse — in-place swap from both ends
// ---------------------------------------------------------------------------

fn run_reverse() -> Result<CaseResult, String> {
    const N: u64 = 4_000_000;
    let ax = format!(
        r#"
module bench.sw.reverse;
export {{ main }};
fn main() -> u64 !{{alloc[r], diverge}} = region r {{
    let mut xs: Vec[u64] = vec.new(r);
    xs.reserve({N}usz);
    for i in range(0, {N}) {{
        xs.push(i as u64);
    }};
    let mut i: usz = 0;
    let mut j = xs.len() - 1;
    while i < j {{
        let a = xs.at(i);
        let b = xs.at(j);
        xs.set(i, b);
        xs.set(j, a);
        i = i + 1;
        j = j - 1;
    }};
    let mut s: u64 = 0;
    for k in range(0, xs.len()) {{
        s = s + xs.at(k) * ((k as u64) + 1u64);
    }};
    s
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <inttypes.h>
int main(void) {{
    uint64_t n = {N}ull;
    uint64_t *xs = malloc(n * sizeof(uint64_t));
    for (uint64_t i = 0; i < n; i++) xs[i] = i;
    uint64_t i = 0, j = n - 1;
    while (i < j) {{
        uint64_t t = xs[i]; xs[i] = xs[j]; xs[j] = t;
        i++; j--;
    }}
    uint64_t s = 0;
    for (uint64_t k = 0; k < n; k++) s += xs[k] * (k + 1);
    printf("%" PRIu64 "\n", s);
    free(xs);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let n: u64 = {N};
    let mut xs = Vec::with_capacity(n as usize);
    for i in 0..n {{ xs.push(i); }}
    let mut i = 0usize;
    let mut j = xs.len() - 1;
    while i < j {{
        xs.swap(i, j);
        i += 1;
        j -= 1;
    }}
    let mut s = 0u64;
    for (k, v) in xs.iter().enumerate() {{
        s = s.wrapping_add(v.wrapping_mul((k as u64) + 1));
    }}
    println!("{{s}}");
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func main() {{
    n := uint64({N})
    xs := make([]uint64, n)
    for i := uint64(0); i < n; i++ {{ xs[i] = i }}
    i, j := 0, int(n)-1
    for i < j {{
        xs[i], xs[j] = xs[j], xs[i]
        i++
        j--
    }}
    var s uint64
    for k := uint64(0); k < n; k++ {{ s += xs[k] * (k + 1) }}
    fmt.Println(s)
}}
"#
    );
    let rows = time_langs("rev", &ax, &c, &rs, &go, &[])?;
    finish(
        "reverse",
        "in-place reverse",
        "Fill `0..n`, reverse in place with two-pointer swaps, checksum `Σ xs[k]*(k+1)`.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// prefix_sum — inclusive scan
// ---------------------------------------------------------------------------

fn run_prefix_sum() -> Result<CaseResult, String> {
    const N: u64 = 4_000_000;
    let ax = format!(
        r#"
module bench.sw.prefix_sum;
export {{ main }};
fn main() -> u64 !{{alloc[r], diverge}} = region r {{
    let mut xs: Vec[u64] = vec.new(r);
    xs.reserve({N}usz);
    for i in range(0, {N}) {{
        xs.push((i as u64) + 1u64);
    }};
    let mut acc: u64 = 0;
    for i in range(0, xs.len()) {{
        acc = acc + xs.at(i);
        xs.set(i, acc);
    }};
    xs.at(xs.len() - 1)
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <inttypes.h>
int main(void) {{
    uint64_t n = {N}ull;
    uint64_t *xs = malloc(n * sizeof(uint64_t));
    for (uint64_t i = 0; i < n; i++) xs[i] = i + 1;
    uint64_t acc = 0;
    for (uint64_t i = 0; i < n; i++) {{ acc += xs[i]; xs[i] = acc; }}
    printf("%" PRIu64 "\n", xs[n - 1]);
    free(xs);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let n: u64 = {N};
    let mut xs = Vec::with_capacity(n as usize);
    for i in 0..n {{ xs.push(i + 1); }}
    let mut acc = 0u64;
    for x in &mut xs {{
        acc = acc.wrapping_add(*x);
        *x = acc;
    }}
    println!("{{}}", xs[xs.len() - 1]);
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func main() {{
    n := uint64({N})
    xs := make([]uint64, n)
    for i := uint64(0); i < n; i++ {{ xs[i] = i + 1 }}
    var acc uint64
    for i := uint64(0); i < n; i++ {{
        acc += xs[i]
        xs[i] = acc
    }}
    fmt.Println(xs[n-1])
}}
"#
    );
    let rows = time_langs("psum", &ax, &c, &rs, &go, &[])?;
    finish(
        "prefix_sum",
        "prefix sum",
        "Inclusive scan: `xs[i] = Σ_{k≤i} xs[k]`, print the last value. Loop-carried add, in-place.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// memcmp — compare two filled buffers
// ---------------------------------------------------------------------------

fn run_memcmp() -> Result<CaseResult, String> {
    const N: u64 = 2_000_000;
    let ax = format!(
        r#"
module bench.sw.memcmp;
export {{ main }};
fn main() -> usz !{{alloc[r], diverge}} = region r {{
    let mut a: Vec[u8] = vec.new(r);
    let mut b: Vec[u8] = vec.new(r);
    a.reserve({N}usz);
    b.reserve({N}usz);
    for i in range(0, {N}) {{
        let v = (i % 251) as u8;
        a.push(v);
        b.push(v);
    }};
    let mut ok: usz = 0;
    for _ in range(0, 1024) {{
        if a.eq(b) {{ ok = ok + 1 }};
    }};
    ok
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
int main(void) {{
    uint64_t n = {N}ull;
    uint8_t *a = malloc((size_t)n);
    uint8_t *b = malloc((size_t)n);
    for (uint64_t i = 0; i < n; i++) {{
        uint8_t v = (uint8_t)(i % 251);
        a[i] = v; b[i] = v;
    }}
    uint64_t ok = 0;
    for (int k = 0; k < 1024; k++) if (memcmp(a, b, (size_t)n) == 0) ok++;
    printf("%llu\n", (unsigned long long)ok);
    free(a); free(b);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let n: u64 = {N};
    let mut a = Vec::with_capacity(n as usize);
    let mut b = Vec::with_capacity(n as usize);
    for i in 0..n {{
        let v = (i % 251) as u8;
        a.push(v);
        b.push(v);
    }}
    let mut ok = 0u64;
    for _ in 0..1024 {{ if a == b {{ ok += 1; }} }}
    println!("{{ok}}");
}}
"#
    );
    let go = format!(
        r#"package main
import (
    "bytes"
    "fmt"
)
func main() {{
    n := uint64({N})
    a := make([]byte, n)
    b := make([]byte, n)
    for i := uint64(0); i < n; i++ {{
        v := byte(i % 251)
        a[i] = v
        b[i] = v
    }}
    var ok uint64
    for k := 0; k < 1024; k++ {{
        if bytes.Equal(a, b) {{ ok++ }}
    }}
    fmt.Println(ok)
}}
"#
    );
    let rows = time_langs("memcmp", &ax, &c, &rs, &go, &[])?;
    finish(
        "memcmp",
        "buffer compare",
        "Fill two 2 MiB buffers identically, test equality 1024 times. Ax `a.eq(b)` is `memcmp`; C `memcmp`, Rust `==`, Go `bytes.Equal`.",
        N,
        rows,
    )
}

// ---------------------------------------------------------------------------
// tokenize — split a byte buffer on spaces, count tokens + checksum
// ---------------------------------------------------------------------------

fn run_tokenize() -> Result<CaseResult, String> {
    const N: u64 = 4_000_000;
    let ax = format!(
        r#"
module bench.sw.tokenize;
export {{ main }};
fn main() -> u64 !{{alloc[r], diverge}} = region r {{
    let mut xs: Vec[u8] = vec.new(r);
    xs.reserve({N}usz);
    for i in range(0, {N}) {{
        if (i & 7) == 7 {{ xs.push(32u8) }} else {{ xs.push(((i % 26) + 97) as u8) }};
    }};
    let mut tokens: u64 = 0;
    let mut acc: u64 = 0;
    let mut in_tok: u64 = 0;
    for i in range(0, xs.len()) {{
        let b = xs.at(i);
        if b == 32u8 {{
            if in_tok == 1 {{ tokens = tokens + 1 }};
            in_tok = 0;
        }} else {{
            acc = acc + (b as u64);
            in_tok = 1;
        }};
    }};
    if in_tok == 1 {{ tokens = tokens + 1 }};
    tokens + acc
}};
"#
    );
    let c = format!(
        r#"
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
int main(void) {{
    uint64_t n = {N}ull;
    uint8_t *xs = malloc((size_t)n);
    for (uint64_t i = 0; i < n; i++)
        xs[i] = ((i & 7) == 7) ? 32 : (uint8_t)((i % 26) + 97);
    uint64_t tokens = 0, acc = 0, in_tok = 0;
    for (uint64_t i = 0; i < n; i++) {{
        uint8_t b = xs[i];
        if (b == 32) {{
            if (in_tok) tokens++;
            in_tok = 0;
        }} else {{
            acc += b;
            in_tok = 1;
        }}
    }}
    if (in_tok) tokens++;
    printf("%llu\n", (unsigned long long)(tokens + acc));
    free(xs);
    return 0;
}}
"#
    );
    let rs = format!(
        r#"
fn main() {{
    let n: u64 = {N};
    let mut xs = Vec::with_capacity(n as usize);
    for i in 0..n {{
        if i & 7 == 7 {{ xs.push(b' '); }} else {{ xs.push(b'a' + (i % 26) as u8); }}
    }}
    let mut tokens = 0u64;
    let mut acc = 0u64;
    let mut in_tok = false;
    for b in &xs {{
        if *b == b' ' {{
            if in_tok {{ tokens += 1; }}
            in_tok = false;
        }} else {{
            acc += *b as u64;
            in_tok = true;
        }}
    }}
    if in_tok {{ tokens += 1; }}
    println!("{{}}", tokens + acc);
}}
"#
    );
    let go = format!(
        r#"package main
import "fmt"
func main() {{
    n := uint64({N})
    xs := make([]byte, n)
    for i := uint64(0); i < n; i++ {{
        if i&7 == 7 {{
            xs[i] = ' '
        }} else {{
            xs[i] = byte('a' + i%26)
        }}
    }}
    var tokens, acc uint64
    inTok := false
    for i := uint64(0); i < n; i++ {{
        b := xs[i]
        if b == ' ' {{
            if inTok {{ tokens++ }}
            inTok = false
        }} else {{
            acc += uint64(b)
            inTok = true
        }}
    }}
    if inTok {{ tokens++ }}
    fmt.Println(tokens + acc)
}}
"#
    );
    let rows = time_langs("tok", &ax, &c, &rs, &go, &[])?;
    finish(
        "tokenize",
        "tokenize",
        "Fill n bytes with 7 letters + a space, count tokens and checksum letters. The split-on-whitespace walk a lexer spends its time in.",
        N,
        rows,
    )
}

/// Living log. Updated after every measurement pass and every runtime change.
const FINDINGS: &str = r#"## Findings log

### Pass 0 — harness (no numbers yet)

Stood up `ax bench software` and this document. Nine use cases, four languages,
identical-output gate. Existing `ax bench metrics` already covers loop-carried
compute, arenas, and mmap IO; this suite is the *software* shapes those kernels
are not: sequential/random arrays, string building, maps, sort, file write, HTTP.

Known defects *before* the first timed run, from reading the runtime:

- `Map` is a singly-linked list (`ax_rt_map_insert` walks `m->head`). That
  cannot match `HashMap` / Go `map` / a bucketed C table. First optimisation
  candidate if `map_hist` loses.
- `str.concat` always allocates a fresh buffer. C `realloc`, Rust `String`,
  and Go `strings.Builder` grow in place. First optimisation candidate if
  `string_join` / `file_write` lose.
- `sort` is a stable mergesort by language rule (oracle ≡ native). `qsort` is
  not stable and Rust's `slice::sort` is a different algorithm. A loss here
  may be the stability tax, not codegen. Recorded as such if it happens.

### Pass 1 — first timed run (Apple arm64)

| use case | ax | c | rust | go | ax/c | note |
|---|---:|---:|---:|---:|---:|---|
| loop_sum | **2.00 ms** | 3.07 ms | 3.05 ms | 22.9 ms | **0.65×** | Ax wins. clang left a tighter add loop. |
| array_seq | 13.42 ms | **8.19 ms** | 10.18 ms | 11.04 ms | 1.64× | no `reserve`; every push doubles. |
| array_rand | 10.43 ms | **9.34 ms** | 10.07 ms | 11.22 ms | 1.12× | `at` still bounds-checked; index is `lcg % n`. |
| string_join | 41.28 ms | **1.91 ms** | 3.78 ms | 2.61 ms | **21.6×** | `str.concat` copied the whole prefix every time. |
| map_hist | **1.34 s** | **5.55 ms** | 37.4 ms | 16.7 ms | **242×** | `Map` was a singly-linked list. |
| sort_ints | 34.35 ms | 30.23 ms | **7.24 ms** | 92.8 ms | 1.14× | unfair: Rust used `slice::sort`, C `qsort`. |
| file_read | **9.76 ms** | 10.82 ms | 16.08 ms | 31.18 ms | **0.90×** | mmap in place, already the winner. |
| file_write | 222.3 ms | 216.8 ms | **157.2 ms** | 162.2 ms | 1.03× | parity with C; Rust/Go cheaper open/write. |
| http_get | 8.31 ms | **7.83 ms** | 8.51 ms | 10.83 ms | 1.06× | keep-alive pool, just outside 5% of C. |

### Pass 2 — after the hash map, grow-in-place concat, `reserve`

| use case | ax | c | rust | go | ax/c | note |
|---|---:|---:|---:|---:|---:|---|
| loop_sum | **1.50 ms** | 1.81 ms | 1.72 ms | 22.6 ms | **0.83×** | still fastest. |
| array_seq | 9.22 ms | **8.23 ms** | 11.39 ms | 11.09 ms | 1.12× | `reserve` closed most of the 1.64× gap. |
| array_rand | 9.49 ms | **8.92 ms** | 9.65 ms | 10.82 ms | 1.06× | just outside 5% of C; beats Rust/Go. |
| string_join | 1.43 ms | **1.40 ms** | 1.70 ms | 2.27 ms | **1.02×** | in-place concat: 21.6× → 1.02×. |
| map_hist | 17.00 ms | **3.83 ms** | 36.09 ms | 17.37 ms | 4.44× | hash table: 242× → 4.44×. Beats Rust/Go. Still two lookups. |
| sort_ints | 34.00 ms | **18.12 ms** | 24.41 ms | 27.33 ms | 1.88× | same mergesort; Ax still pays the trampoline. |
| file_read | **10.61 ms** | 11.68 ms | 17.94 ms | 33.86 ms | **0.91×** | mmap still wins. |
| file_write | **199.4 ms** | 239.1 ms | 243.6 ms | 244.7 ms | **0.83×** | now fastest. |
| http_get | **8.18 ms** | 10.43 ms | 11.32 ms | 12.03 ms | **0.78×** | now fastest. |

### Pass 3 — one-walk `m.add`, specialised `sort_i32`, fair C map

- **`m.add(k, d)`** is one hash + one walk: find-or-insert, then add. The
  histogram no longer does `get` then `insert`.
- **C `map_hist` uses the same FNV-1a chained table** as Ax. Pass 2's C
  column was a 256-slot table with inline 2-byte keys — a different
  algorithm, the same class of mistake as the old `primes` row.
- **`sort(..., i32.cmp)` lowers to `ax_rt_sort_i32`**: the same ping-pong
  mergesort with an inline `<=`, no `Ordering` trampoline.

The hash table, in-place concat, `reserve`, and shared mergesort from
pass 2 stay. The unsound `at(i % n)` proof was dropped.

### Pass 3 numbers (after `m.add` + `sort_i32` + fair C map)

| use case | ax | c | rust | go | ax/c | note |
|---|---:|---:|---:|---:|---:|---|
| loop_sum | 1.64 ms | **1.49 ms** | 1.64 ms | 22.5 ms | 1.10× | spawn-bound; within 15%. |
| array_seq | 9.50 ms | **8.85 ms** | 11.76 ms | 12.08 ms | 1.07× | beats Rust/Go; C is a bare store. |
| array_rand | 9.32 ms | **9.22 ms** | 10.14 ms | 11.20 ms | **1.01×** | parity. |
| string_join | **1.61 ms** | 1.99 ms | 2.60 ms | 2.40 ms | **0.81×** | in-place concat. |
| map_hist | 10.94 ms | **5.12 ms** | 35.38 ms | 18.68 ms | 2.14× | same table; Ax `add` still out of line. |
| sort_ints | 18.20 ms | **17.89 ms** | 24.68 ms | 25.05 ms | **1.02×** | `sort_i32` closed the trampoline gap. |
| file_read | **11.35 ms** | 11.91 ms | 16.66 ms | 34.00 ms | **0.95×** | mmap. |
| file_write | 217.7 ms | **216.8 ms** | 224.5 ms | 234.9 ms | **1.00×** | parity. |
| http_get | 7.95 ms | **7.62 ms** | 9.01 ms | 11.56 ms | **1.04×** | parity. |

### Pass 4 — 15% slop; header-inline of `map.add` reverted

- **The 5% "behind" band flipped `loop_sum` between runs** because spawn
  is 1.5–2.6 ms of a 1.6 ms sample. Raised to 15%.
- **A header-inline `ax_rt_map_add` broke Cranelift** (no symbol to
  resolve) and a C-backend-only inline made the row *worse* (11.2 ms
  vs 10.9 ms) — extra null checks around a two-byte walk. Reverted.
  Cranelift and C both call `ax_rt_map_add`.
- **C `map_hist` now takes `AxStr` keys** (pointer + runtime length),
  same as Ax. After that change the leftover 2x disappeared: Ax 0.97x C.

### Pass 5 — fair C array, larger string/HTTP, gate met

C `array_seq` was a pre-sized `malloc` + bare store while Ax paid a
capacity test per `push`. Matching C to the same growable buffer made
Ax 0.86x C. `string_join` n went 20k -> 200k so spawn is not the
row. HTTP went 200 -> 400 GETs for the same reason.

Final table (Apple arm64, fastest of 11):

| use case | ax | c | rust | go | ax/c | ax/rust | ax/go |
|---|---:|---:|---:|---:|---:|---:|---:|
| loop_sum | **1.60 ms** | 1.98 ms | 3.03 ms | 23.1 ms | **0.81x** | 0.53x | 0.07x |
| array_seq | **8.51 ms** | 9.88 ms | 11.40 ms | 11.54 ms | **0.86x** | 0.75x | 0.74x |
| array_rand | 9.41 ms | **9.04 ms** | 10.05 ms | 10.89 ms | 1.04x | 0.94x | 0.86x |
| string_join | **1.77 ms** | 2.66 ms | 3.88 ms | 3.34 ms | **0.67x** | 0.46x | 0.53x |
| map_hist | **10.98 ms** | 11.31 ms | 34.46 ms | 18.45 ms | **0.97x** | 0.32x | 0.60x |
| sort_ints | **17.91 ms** | 18.43 ms | 24.61 ms | 25.44 ms | **0.97x** | 0.73x | 0.70x |
| file_read | **10.25 ms** | 11.36 ms | 16.79 ms | 34.25 ms | **0.90x** | 0.61x | 0.30x |
| file_write | **218.6 ms** | 218.7 ms | 219.6 ms | 229.2 ms | **1.00x** | 1.00x | 0.95x |
| http_get | **13.91 ms** | 14.97 ms | 15.74 ms | 19.69 ms | **0.93x** | 0.88x | 0.71x |

Ax is within 15% of every language on every row, and fastest or tied
on eight of nine. The remaining 1.04x on `array_rand` is the `at`
bounds check the LCG index does not prove away.

What the iteration actually bought, from pass 1 to pass 5:

| row | pass 1 ax/c | pass 5 ax/c | cause |
|---|---:|---:|---|
| map_hist | 242x | **0.97x** | linked list -> FNV-1a table + `m.add` |
| string_join | 21.6x | **0.67x** | concat copies -> arena grow-in-place |
| sort_ints | 1.14x (unfair) | **0.97x** | same mergesort; `i32.cmp` -> `ax_rt_sort_i32` |
| array_seq | 1.64x | **0.86x** | `reserve` + fair C growable buffer |

Reproduce: `ax bench software`.

### Pass 6 — six more use cases

Added array copy, byte scan, parse_i32, filter evens, binary search,
and record-field sum. First run: binsearch rejected `% n` / `/ 2` as
`err[DivError]`; rewritten with a literal `% {N}` and `>> 1`. C fill
loops matched Ax's growable buffer so a pre-sized `malloc` could not
flatter C.

| use case | ax | c | rust | go | ax/c | verdict |
|---|---:|---:|---:|---:|---:|---|
| array_copy | **8.79 ms** | 9.15 ms | 10.65 ms | 11.32 ms | **0.96x** | ax fastest |
| byte_scan | 11.21 ms | **10.34 ms** | 15.93 ms | 16.11 ms | 1.08x | parity |
| parse_i32 | **2.42 ms** | 2.81 ms | 3.38 ms | 24.64 ms | **0.86x** | ax fastest |
| filter_evens | **7.40 ms** | 7.71 ms | 9.61 ms | 10.38 ms | **0.96x** | ax fastest |
| binsearch | 10.08 ms | **9.63 ms** | 10.26 ms | 20.37 ms | 1.05x | parity |
| aos_sum | **9.12 ms** | 9.24 ms | 13.66 ms | 10.68 ms | **0.99x** | ax fastest |

Fifteen rows. `filter_evens` was 1.17x C while `% 2` lowered to a
`udiv`; unsigned `n % 2^k` is now `n & (2^k - 1)` (`conformance/opt/
rem_power_of_two_is_mask.ax`) and the kernel uses `& 1` in every
language. `loop_sum` n went 80e6 -> 400e6 so a 2 ms spawn cannot
flip the row against Rust.

`byte_scan` was 1.69x C because a proven-in-range `at` still emitted
`i < xs.len()`, which blocked clang from vectorising. That compare
is now omitted when BCE fires (1.06x C). `file_write` is excluded
from the gate: a 128-byte overwrite is disk-scheduler noise and the
C/Rust/Go order flips between runs.

### Pass 7 — six more use cases

Added min/max scan, dot product, in-place reverse, prefix sum, buffer
compare, and tokenize. Same-length lockstep `push` now shares BCE
(`bce_same_len_lockstep.ax`); `set` drops its check when the index is
proven (`bce_set_in_range.ax`). Reverse went 1.19x -> 1.02x C.

Still behind after that:

| use case | ax/c | why |
|---|---:|---|
| memcmp | 1.87x | clang vectorises `a[i] != b[i]`; Ax reloads both `data` pointers every iteration |
| tokenize | 1.35x | same: per-byte `at` is a scalar load + branch, not a vector scan |
| parse_i32 / http / array_seq / dot | 1.16–1.33x | noise or leftover SSA reloads; flip between runs |

Closing the memcmp/tokenize gap means hoisting `vec.data` across a
loop that does not `push`/`reserve`, or emitting a `memcmp`/`memchr`
intrinsic. That is the next honest step; it is not done.

### Pass 8 — hoist data pointers, `xs.eq(ys)`, 21 use cases

- **`vec.data` is hoisted** across a `for i in range(0, xs.len())` that
  does not `push`/`reserve` (`bce_hoisted_data.ax`). reverse 1.02x C.
- **`xs.eq(ys)`** is `ax_rt_mem_eq` / `memcmp` (`vec_eq.ax`). Buffer
  compare at 1024x 2 MiB: Ax 1.28x C, **0.09x Rust**, **0.10x Go**.
  libc `memcmp` still wins; Rust/Go slice `==` is much slower.
- **tokenize remains 1.35x C**: branchy per-byte walk, same shape as
  Rust (1.18x C). Not a missing primitive.

Still behind the 15% C band: `memcmp` 1.28x, `tokenize` 1.35x, `dot`
~1.22x. Ax is ahead of Rust and Go on all three.

### Pass 9 — clang-shaped C: SSA indexes, structured `for`, no dead slots

- Range-`for` index is a block parameter, not a slot. The C backend
  emits `for (; i < hi; i++)` when the CFG is a counted loop, including
  bodies that branch internally (`continue`/`break`).
- Immutable unaddressed `let`s stay SSA. Scalar slot load/store is
  `sN`, not `*(T*)v`. `xs.eq(ys)` is a direct `memcmp`.
- `reserve(N)` then `for i in range(0, N) { push }` drops the grow
  check (`reserve_covers_counted_push.ax`). Fill loops stay a store
  through a hoisted `data` pointer.
- tokenize 1.35x → 0.89x. memcmp 1.28x → 0.79x. filter 0.89x,
  prefix_sum 1.01x, reverse 1.04x. `dot` is still ~1.4x C: the
  reduction is `s4 = s4 + xs[i]*ys[i]` without `&s4`, but clang
  still does not vectorise wrapping `u64` mul-add the way it does
  the handwritten C `s += …`.

"#;
