//! Standalone source-to-source REST router for Ax.
//!
//! The core language only sees the generated `http.serve_handler` program.
//! Route declarations and response conveniences belong to this package.

use std::collections::{BTreeMap, HashSet};

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Route {
    pub method: String,
    pub path: String,
    pub handler: String,
    pub param: Option<String>,
    pub params: Vec<String>,
    pub pattern: String,
    pub query_params: Vec<String>,
    pub header_params: Vec<String>,
    pub session_params: Vec<String>,
    pub body_type: Option<String>,
}

#[derive(Clone, Debug)]
pub struct App {
    pub port: u16,
    pub routes: Vec<Route>,
    pub body_limit: u32,
    pub timeout_ms: u32,
    pub cors_origin: Option<String>,
    pub auth_header: Option<String>,
    pub auth_value: Option<String>,
    pub session_cookie: Option<String>,
}

pub fn compile(source: &str) -> Result<(App, String), String> {
    let app = parse_directives(source)?;
    if source.lines().any(|line| {
        let line = line.trim_start();
        line.starts_with("fn main(") || line.starts_with("fn main ")
    }) {
        return Err("ax-api owns `main`; remove the application main function".into());
    }
    let mut generated = rewrite_response_helpers(source);
    generated.push_str("\n\n//! Generated by the standalone ax-api framework.\n");
    generated.push_str(&generate_dispatch(&app));
    Ok((app, generated))
}

fn parse_directives(source: &str) -> Result<App, String> {
    let mut port = 8080u16;
    let mut body_limit = 3840u32;
    let mut timeout_ms = 0u32;
    let mut cors_origin = None;
    let mut auth_header = None;
    let mut auth_value = None;
    let mut session_cookie = None;
    let mut routes = Vec::new();
    let mut seen = HashSet::new();
    for (line_index, line) in source.lines().enumerate() {
        let Some(directive) = line.trim().strip_prefix("// ax-api ") else {
            continue;
        };
        if let Some(value) = directive.strip_prefix("port ") {
            port = value.trim().parse::<u16>().map_err(|_| {
                format!(
                    "line {}: port must be an integer from 0 to 65535",
                    line_index + 1
                )
            })?;
            continue;
        }
        if let Some(value) = directive.strip_prefix("body_limit ") {
            body_limit = value.trim().parse::<u32>().map_err(|_| {
                format!(
                    "line {}: body_limit must be a positive integer",
                    line_index + 1
                )
            })?;
            if body_limit == 0 || body_limit > 3840 {
                return Err(format!(
                    "line {}: body_limit must be between 1 and 3840 bytes",
                    line_index + 1
                ));
            }
            continue;
        }
        if let Some(value) = directive.strip_prefix("timeout_ms ") {
            timeout_ms = value.trim().parse::<u32>().map_err(|_| {
                format!(
                    "line {}: timeout_ms must be a non-negative integer",
                    line_index + 1
                )
            })?;
            continue;
        }
        if let Some(value) = directive.strip_prefix("cors ") {
            let value = value.trim();
            if value.is_empty() {
                return Err(format!("line {}: cors origin is empty", line_index + 1));
            }
            cors_origin = Some(value.into());
            continue;
        }
        if let Some(value) = directive.strip_prefix("auth ") {
            let (header, expected) = value
                .trim()
                .split_once('=')
                .ok_or_else(|| format!("line {}: expected `auth Header=value`", line_index + 1))?;
            if header.is_empty() || expected.is_empty() {
                return Err(format!(
                    "line {}: auth header and value are required",
                    line_index + 1
                ));
            }
            auth_header = Some(header.into());
            auth_value = Some(expected.into());
            continue;
        }
        if let Some(value) = directive.strip_prefix("session ") {
            let value = value.trim();
            if value.is_empty() {
                return Err(format!(
                    "line {}: session cookie name is empty",
                    line_index + 1
                ));
            }
            session_cookie = Some(value.into());
            continue;
        }
        if let Some(value) = directive.strip_prefix("middleware ") {
            let (kind, config) = value.trim().split_once(' ').ok_or_else(|| {
                format!(
                    "line {}: expected `middleware auth|cors|session ...`",
                    line_index + 1
                )
            })?;
            match kind {
                "auth" => {
                    let (header, expected) = config.split_once('=').ok_or_else(|| {
                        format!(
                            "line {}: expected `middleware auth Header=value`",
                            line_index + 1
                        )
                    })?;
                    auth_header = Some(header.into());
                    auth_value = Some(expected.into());
                }
                "cors" => cors_origin = Some(config.trim().into()),
                "session" => session_cookie = Some(config.trim().into()),
                _ => {
                    return Err(format!(
                        "line {}: unknown middleware `{kind}`",
                        line_index + 1
                    ))
                }
            }
            continue;
        }
        let (left, handler) = directive.split_once(" -> ").ok_or_else(|| {
            format!(
                "line {}: expected `// ax-api METHOD /path -> handler`",
                line_index + 1
            )
        })?;
        let (method, path) = left
            .split_once(' ')
            .ok_or_else(|| format!("line {}: expected an HTTP method and path", line_index + 1))?;
        let method = method.to_ascii_uppercase();
        if !matches!(method.as_str(), "GET" | "POST" | "PUT" | "PATCH" | "DELETE") {
            return Err(format!(
                "line {}: unsupported method `{method}`",
                line_index + 1
            ));
        }
        let mut parts = handler.split_whitespace();
        let handler_name = parts
            .next()
            .ok_or_else(|| format!("line {}: missing handler name", line_index + 1))?;
        validate_handler(handler_name, line_index + 1)?;
        let mut query_params = Vec::new();
        let mut header_params = Vec::new();
        let mut session_params = Vec::new();
        let mut body_type = None;
        for option in parts {
            let (key, value) = option.split_once('=').ok_or_else(|| {
                format!("line {}: route option must be key=value", line_index + 1)
            })?;
            if value.is_empty() {
                return Err(format!(
                    "line {}: route option `{key}` is empty",
                    line_index + 1
                ));
            }
            match key {
                "query" => query_params.push(value.into()),
                "header" => header_params.push(value.into()),
                "session" => session_params.push(value.into()),
                "body" => {
                    validate_handler(value, line_index + 1)?;
                    body_type = Some(value.into());
                }
                _ => {
                    return Err(format!(
                        "line {}: unknown route option `{key}`",
                        line_index + 1
                    ))
                }
            }
        }
        let path_info = validate_path(path.trim(), line_index + 1)?;
        if path.trim() == "/openapi.json" {
            return Err(format!(
                "line {}: `/openapi.json` is generated by ax-api",
                line_index + 1
            ));
        }
        let shape = route_shape(path.trim());
        if !seen.insert((method.clone(), shape)) {
            return Err(format!("line {}: duplicate route", line_index + 1));
        }
        routes.push(Route {
            method,
            path: path.trim().into(),
            handler: handler_name.into(),
            param: path_info.params.first().cloned(),
            params: path_info.params,
            pattern: path_info.pattern,
            query_params,
            header_params,
            session_params,
            body_type,
        });
    }
    if routes.is_empty() {
        return Err("no routes found; add `// ax-api GET / -> handler`".into());
    }
    Ok(App {
        port,
        routes,
        body_limit,
        timeout_ms,
        cors_origin,
        auth_header,
        auth_value,
        session_cookie,
    })
}

fn validate_handler(handler: &str, line: usize) -> Result<(), String> {
    let mut chars = handler.chars();
    let Some(first) = chars.next() else {
        return Err(format!("line {line}: missing handler name"));
    };
    if !(first == '_' || first.is_ascii_alphabetic())
        || !chars.all(|c| c == '_' || c.is_ascii_alphanumeric())
    {
        return Err(format!("line {line}: invalid handler name `{handler}`"));
    }
    Ok(())
}

struct PathInfo {
    params: Vec<String>,
    pattern: String,
}

fn validate_path(path: &str, line: usize) -> Result<PathInfo, String> {
    if !path.starts_with('/') || path.contains('?') || path.contains('#') {
        return Err(format!(
            "line {line}: route paths must start with `/` and omit query/fragment"
        ));
    }
    let mut params = Vec::new();
    let mut pattern = String::with_capacity(path.len());
    let segments = path.split('/');
    for (index, segment) in segments.enumerate() {
        if segment.is_empty() {
            pattern.push('/');
            continue;
        }
        if segment == "*" || segment.starts_with('*') {
            if index + 1 != path.split('/').count() || segment.len() < 2 {
                return Err(format!("line {line}: wildcard must be `*name` at the end"));
            }
            let name = &segment[1..];
            validate_handler(name, line)?;
            params.push(name.into());
            pattern.push('*');
            if index + 1 != path.split('/').count() {
                pattern.push('/');
            }
            continue;
        }
        if segment.starts_with('{') || segment.ends_with('}') {
            if !(segment.starts_with('{') && segment.ends_with('}') && segment.len() > 2) {
                return Err(format!("line {line}: malformed path parameter"));
            }
            let name = &segment[1..segment.len() - 1];
            validate_handler(name, line)?;
            params.push(name.into());
            pattern.push_str("{}");
            if index + 1 != path.split('/').count() {
                pattern.push('/');
            }
            continue;
        }
        if segment.contains('{') || segment.contains('}') || segment.contains('*') {
            return Err(format!(
                "line {line}: path parameter must occupy a full segment"
            ));
        }
        pattern.push_str(segment);
        if index + 1 != path.split('/').count() {
            pattern.push('/');
        }
    }
    Ok(PathInfo { params, pattern })
}

fn route_shape(path: &str) -> String {
    path.split('/')
        .map(|segment| {
            if segment.starts_with('{') && segment.ends_with('}') {
                "{}"
            } else if segment.starts_with('*') {
                "*"
            } else {
                segment
            }
        })
        .collect::<Vec<_>>()
        .join("/")
}

fn ax_string(value: &str) -> String {
    let mut out = String::from("\"");
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn path_condition(route: &Route, request: &str) -> String {
    if route.params.is_empty() {
        return format!("{request}.path == {}", ax_string(&route.path));
    }
    if route.params.len() != 1 || route.pattern.contains('*') || !route.pattern.ends_with("{}") {
        return format!(
            "http.path_match({request}.path, {})",
            ax_string(&route.pattern)
        );
    }
    let open = route.path.find('{').unwrap();
    let prefix = &route.path[..open];
    let prefix_string = ax_string(prefix);
    format!(
        "str.starts_with({request}.path, {prefix_string}) && {request}.path != {prefix_string} && !str.contains(str.drop({request}.path, {open}usz), \"/\")"
    )
}

fn handler_call(route: &Route) -> String {
    if route.body_type.is_some() {
        return format!("__ax_api_body_{}(request)", route.handler);
    }
    format!("{}({})", route.handler, handler_arguments(route).join(", "))
}

fn handler_arguments(route: &Route) -> Vec<String> {
    let mut args = vec!["request".to_string()];
    if route.params.len() == 1 && route.pattern.ends_with("{}") && !route.pattern.contains('*') {
        let open = route.path.find('{').unwrap();
        args.push(format!("str.drop(request.path, {open}usz)"));
    } else {
        for (index, _) in route.params.iter().enumerate() {
            args.push(format!(
                "http.path_param(request.path, {}, {}u16)",
                ax_string(&route.pattern),
                index
            ));
        }
    }
    for query in &route.query_params {
        args.push(format!(
            "http.query_param(request.query, {})",
            ax_string(query)
        ));
    }
    for header in &route.header_params {
        args.push(format!(
            "http.header(request.headers, {})",
            ax_string(header)
        ));
    }
    for session in &route.session_params {
        args.push(format!(
            "http.cookie(request.headers, {})",
            ax_string(session)
        ));
    }
    if let Some(body_type) = &route.body_type {
        args.push(format!("json.decode(test.alloc, request.body)"));
        let _ = body_type;
    }
    args
}

fn generate_dispatch(app: &App) -> String {
    let mut out = String::new();
    for route in &app.routes {
        if route.body_type.is_some() {
            out.push_str(&format!(
                "fn __ax_api_body_{}(request: http.Request) -> http.Response !{{alloc[a]}} =\n    match attempt {}({}) {{\n        Ok(response) => response;\n        Err(_) => http.response(422u16, \"{{\\\"error\\\":{{\\\"code\\\":\\\"invalid_json\\\",\\\"message\\\":\\\"Invalid JSON body\\\"}}}}\");\n    }};\n\n",
                route.handler,
                route.handler,
                handler_arguments(route).join(", ")
            ));
        }
    }
    out.push_str("fn __ax_api_dispatch(request: http.Request) -> http.Response !{alloc[a]} =\n");
    let mut first = true;
    if let Some(header) = &app.auth_header {
        let expected = app.auth_value.as_deref().unwrap_or("");
        out.push_str(&format!(
            "    if http.header(request.headers, {}) != {} {{\n        http.response(401u16, \"{{\\\"error\\\":{{\\\"code\\\":\\\"unauthorized\\\",\\\"message\\\":\\\"Unauthorized\\\"}}}}\")\n    }}\n",
            ax_string(header), ax_string(expected)
        ));
        first = false;
    }
    if let Some(cookie) = &app.session_cookie {
        let keyword = if first { "    if" } else { "    else if" };
        out.push_str(&format!(
            "{keyword} http.cookie(request.headers, {}) == \"\" {{\n        http.response(401u16, \"{{\\\"error\\\":{{\\\"code\\\":\\\"session_required\\\",\\\"message\\\":\\\"Session required\\\"}}}}\")\n    }}\n",
            ax_string(cookie)
        ));
        first = false;
    }
    for (index, route) in app.routes.iter().enumerate() {
        let keyword = if first && index == 0 {
            "    if"
        } else {
            "    else if"
        };
        out.push_str(&format!(
            "{keyword} request.method == {} && {} {{\n        {}\n    }}\n",
            ax_string(&route.method),
            path_condition(route, "request"),
            handler_call(route)
        ));
    }
    let openapi = ax_string(&openapi_document(app));
    let docs = ax_string(&docs_html());
    out.push_str(&format!(
        "    else if request.method == \"GET\" && request.path == \"/openapi.json\" {{\n        http.response(200u16, {openapi})\n    }}\n    else if request.method == \"GET\" && request.path == \"/docs\" {{\n        http.response(200u16, {docs})\n    }}\n"
    ));
    let paths = app
        .routes
        .iter()
        .map(|route| path_condition(route, "request"))
        .collect::<Vec<_>>()
        .into_iter()
        .chain(std::iter::once(
            "request.path == \"/openapi.json\" || request.path == \"/docs\"".into(),
        ))
        .collect::<Vec<_>>()
        .join(" || ");
    out.push_str(&format!(
        "    else if {paths} {{\n        if request.method == \"OPTIONS\" {{\n            http.response(204u16, \"\")\n        }} else {{\n            http.response(405u16, \"{{\\\"error\\\":{{\\\"code\\\":\\\"method_not_allowed\\\",\\\"message\\\":\\\"Method not allowed\\\"}}}}\")\n        }}\n    }} else {{\n        http.response(404u16, \"{{\\\"error\\\":{{\\\"code\\\":\\\"not_found\\\",\\\"message\\\":\\\"Route not found\\\"}}}}\")\n    }};\n\nfn main() -> unit !{{io[net], abort}} = {} ;\n",
        if app.body_limit == 3840 && app.timeout_ms == 0 && app.cors_origin.is_none() {
            format!("http.serve_handler({}u16, __ax_api_dispatch)", app.port)
        } else {
            format!(
                "http.serve_handler_config({}u16, __ax_api_dispatch, {}u32, {}u32, {})",
                app.port,
                app.body_limit,
                app.timeout_ms,
                ax_string(app.cors_origin.as_deref().unwrap_or(""))
            )
        }
    ));
    out
}

fn docs_html() -> String {
    "<!doctype html><html><head><meta charset=\"utf-8\"><title>Ax API</title>\
     <style>body{font:16px system-ui;margin:2rem;max-width:60rem}code{background:#eee;padding:.2rem}.route{padding:.5rem;border-bottom:1px solid #ddd}</style>\
     </head><body><h1>Ax API</h1><p>Generated interactive route reference.</p><div id=\"routes\">Loading…</div>\
     <script>fetch('/openapi.json').then(r=>r.json()).then(x=>{let e=document.getElementById('routes');for(let p in x.paths)for(let m in x.paths[p]){let d=x.paths[p][m];e.innerHTML+=`<div class=route><code>${m.toUpperCase()} ${p}</code> — ${d.operationId}</div>`}})</script>\
     </body></html>".into()
}

fn json_string(value: &str) -> String {
    let mut out = String::from("\"");
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn openapi_document(app: &App) -> String {
    let mut paths: BTreeMap<&str, Vec<&Route>> = BTreeMap::new();
    for route in &app.routes {
        paths.entry(&route.path).or_default().push(route);
    }
    let mut out = String::from(
        "{\"openapi\":\"3.1.0\",\"info\":{\"title\":\"Ax API\",\"version\":\"0.1.0\"},\"paths\":{",
    );
    for (path_index, (path, routes)) in paths.iter().enumerate() {
        if path_index > 0 {
            out.push(',');
        }
        out.push_str(&json_string(path));
        out.push_str(":{");
        for (route_index, route) in routes.iter().enumerate() {
            if route_index > 0 {
                out.push(',');
            }
            out.push_str(&json_string(&route.method.to_ascii_lowercase()));
            out.push_str(":{\"operationId\":");
            out.push_str(&json_string(&route.handler));
            if !route.params.is_empty() {
                out.push_str(",\"parameters\":[");
                for (param_index, param) in route.params.iter().enumerate() {
                    if param_index > 0 {
                        out.push(',');
                    }
                    out.push_str("{\"name\":");
                    out.push_str(&json_string(param));
                    out.push_str(
                        ",\"in\":\"path\",\"required\":true,\"schema\":{\"type\":\"string\"}}",
                    );
                }
                out.push(']');
            }
            out.push_str(",\"responses\":{\"200\":{\"description\":\"Success\"}}}");
        }
        out.push('}');
    }
    out.push_str("}}");
    out
}

struct JsonLiteralParser<'a> {
    source: &'a str,
    position: usize,
}

impl<'a> JsonLiteralParser<'a> {
    fn new(source: &'a str) -> Self {
        Self {
            source,
            position: 0,
        }
    }

    fn parse(mut self) -> Option<String> {
        self.skip_whitespace();
        if !matches!(self.peek(), Some(b'{' | b'[')) {
            return None;
        }
        let value = self.value()?;
        self.skip_whitespace();
        if self.position == self.source.len() && ax::interp::json_accepts(&value) {
            Some(value)
        } else {
            None
        }
    }

    fn value(&mut self) -> Option<String> {
        self.skip_whitespace();
        match self.peek()? {
            b'{' => self.object(),
            b'[' => self.array(),
            b'"' => self.string(),
            b'-' | b'0'..=b'9' => self.number(),
            b't' => self.keyword("true"),
            b'f' => self.keyword("false"),
            b'n' => self.keyword("null"),
            _ => None,
        }
    }

    fn object(&mut self) -> Option<String> {
        self.position += 1;
        let mut out = String::from("{");
        self.skip_whitespace();
        if self.take(b'}') {
            out.push('}');
            return Some(out);
        }
        loop {
            self.skip_whitespace();
            let key = if self.peek() == Some(b'"') {
                self.string()?
            } else {
                json_string(&self.identifier()?)
            };
            self.skip_whitespace();
            if !self.take(b':') {
                return None;
            }
            let value = self.value()?;
            out.push_str(&key);
            out.push(':');
            out.push_str(&value);
            self.skip_whitespace();
            if self.take(b'}') {
                out.push('}');
                return Some(out);
            }
            if !self.take(b',') {
                return None;
            }
            self.skip_whitespace();
            if self.take(b'}') {
                out.push('}');
                return Some(out);
            }
            out.push(',');
        }
    }

    fn array(&mut self) -> Option<String> {
        self.position += 1;
        let mut out = String::from("[");
        self.skip_whitespace();
        if self.take(b']') {
            out.push(']');
            return Some(out);
        }
        loop {
            out.push_str(&self.value()?);
            self.skip_whitespace();
            if self.take(b']') {
                out.push(']');
                return Some(out);
            }
            if !self.take(b',') {
                return None;
            }
            self.skip_whitespace();
            if self.take(b']') {
                out.push(']');
                return Some(out);
            }
            out.push(',');
        }
    }

    fn string(&mut self) -> Option<String> {
        let start = self.position;
        if !self.take(b'"') {
            return None;
        }
        while let Some(byte) = self.peek() {
            self.position += 1;
            if byte == b'\\' {
                if self.position >= self.source.len() {
                    return None;
                }
                self.position += 1;
            } else if byte == b'"' {
                return Some(self.source[start..self.position].to_string());
            }
        }
        None
    }

    fn number(&mut self) -> Option<String> {
        let start = self.position;
        while let Some(byte) = self.peek() {
            if byte.is_ascii_whitespace() || matches!(byte, b',' | b']' | b'}') {
                break;
            }
            self.position += 1;
        }
        (self.position > start).then(|| self.source[start..self.position].to_string())
    }

    fn keyword(&mut self, keyword: &str) -> Option<String> {
        if self.source[self.position..].starts_with(keyword) {
            self.position += keyword.len();
            Some(keyword.to_string())
        } else {
            None
        }
    }

    fn identifier(&mut self) -> Option<String> {
        let start = self.position;
        let first = self.peek()?;
        if !(first == b'_' || first.is_ascii_alphabetic()) {
            return None;
        }
        self.position += 1;
        while matches!(
            self.peek(),
            Some(b'_' | b'0'..=b'9' | b'a'..=b'z' | b'A'..=b'Z')
        ) {
            self.position += 1;
        }
        Some(self.source[start..self.position].to_string())
    }

    fn skip_whitespace(&mut self) {
        while self.peek().is_some_and(|byte| byte.is_ascii_whitespace()) {
            self.position += 1;
        }
    }

    fn take(&mut self, expected: u8) -> bool {
        if self.peek() == Some(expected) {
            self.position += 1;
            true
        } else {
            false
        }
    }

    fn peek(&self) -> Option<u8> {
        self.source.as_bytes().get(self.position).copied()
    }
}

fn matching_call_end(source: &str, open: usize) -> Option<usize> {
    let bytes = source.as_bytes();
    let mut depth = 0usize;
    let mut quote = None;
    let mut position = open;
    while position < bytes.len() {
        if let Some(active_quote) = quote {
            if bytes[position] == b'\\' {
                position += 1;
            } else if bytes[position] == active_quote {
                quote = None;
            }
        } else {
            match bytes[position] {
                b'"' | b'`' => quote = Some(bytes[position]),
                b'(' => depth += 1,
                b')' => {
                    depth -= 1;
                    if depth == 0 {
                        return Some(position);
                    }
                }
                _ => {}
            }
        }
        position += 1;
    }
    None
}

fn top_level_comma(source: &str) -> Option<usize> {
    let bytes = source.as_bytes();
    let mut depths = [0usize; 3];
    let mut quote = None;
    let mut position = 0;
    while position < bytes.len() {
        if let Some(active_quote) = quote {
            if bytes[position] == b'\\' {
                position += 1;
            } else if bytes[position] == active_quote {
                quote = None;
            }
        } else {
            match bytes[position] {
                b'"' | b'`' => quote = Some(bytes[position]),
                b'(' => depths[0] += 1,
                b')' => depths[0] = depths[0].checked_sub(1)?,
                b'[' => depths[1] += 1,
                b']' => depths[1] = depths[1].checked_sub(1)?,
                b'{' => depths[2] += 1,
                b'}' => depths[2] = depths[2].checked_sub(1)?,
                b',' if depths == [0, 0, 0] => return Some(position),
                _ => {}
            }
        }
        position += 1;
    }
    None
}

fn rewrite_structured_response_literals(source: &str) -> String {
    let helpers = ["api.ok(", "api.created(", "api.stream(", "api.json("];
    let bytes = source.as_bytes();
    let mut out = String::with_capacity(source.len());
    let mut position = 0;
    let mut in_string = false;
    let mut in_comment = false;
    while position < bytes.len() {
        if in_comment {
            let byte = bytes[position];
            out.push(byte as char);
            position += 1;
            if byte == b'\n' {
                in_comment = false;
            }
            continue;
        }
        if in_string {
            let byte = bytes[position];
            out.push(byte as char);
            position += 1;
            if byte == b'\\' && position < bytes.len() {
                out.push(bytes[position] as char);
                position += 1;
            } else if byte == b'"' {
                in_string = false;
            }
            continue;
        }
        if bytes[position] == b'"' {
            in_string = true;
            out.push('"');
            position += 1;
            continue;
        }
        if bytes.get(position..position + 2) == Some(b"//") {
            in_comment = true;
            out.push_str("//");
            position += 2;
            continue;
        }
        let rest = &source[position..];
        let Some(helper) = helpers.iter().find(|helper| rest.starts_with(**helper)) else {
            let character = rest.chars().next().unwrap();
            out.push(character);
            position += character.len_utf8();
            continue;
        };
        let open = position + helper.len() - 1;
        let Some(close) = matching_call_end(source, open) else {
            out.push_str(helper);
            position += helper.len();
            continue;
        };
        let arguments = &source[open + 1..close];
        let (prefix, body) = if *helper == "api.json(" {
            let Some(comma) = top_level_comma(arguments) else {
                out.push_str(helper);
                position += helper.len();
                continue;
            };
            (&arguments[..=comma], &arguments[comma + 1..])
        } else {
            ("", arguments)
        };
        let Some(json) = JsonLiteralParser::new(body).parse() else {
            out.push_str(helper);
            position += helper.len();
            continue;
        };
        out.push_str(helper);
        out.push_str(prefix);
        if !prefix.is_empty() {
            out.push(' ');
        }
        out.push_str(&ax_string(&json));
        out.push(')');
        position = close + 1;
    }
    out
}

fn rewrite_response_helpers(source: &str) -> String {
    let source = rewrite_structured_response_literals(source);
    let replacements = [
        ("api.ok(", "http.response(200u16, "),
        ("api.created(", "http.response(201u16, "),
        ("api.stream(", "http.response_stream(200u16, "),
        ("api.json(", "http.response("),
        ("api.no_content()", "http.response(204u16, \"\")"),
        (
            "api.bad_request()",
            "http.response(400u16, \"{\\\"error\\\":{\\\"code\\\":\\\"bad_request\\\",\\\"message\\\":\\\"Bad request\\\"}}\")",
        ),
        (
            "api.not_found()",
            "http.response(404u16, \"{\\\"error\\\":{\\\"code\\\":\\\"not_found\\\",\\\"message\\\":\\\"Resource not found\\\"}}\")",
        ),
    ];
    let bytes = source.as_bytes();
    let mut out = String::with_capacity(source.len() + 128);
    let mut i = 0;
    let mut in_string = false;
    let mut in_comment = false;
    while i < bytes.len() {
        if in_comment {
            let c = bytes[i] as char;
            out.push(c);
            i += 1;
            if c == '\n' {
                in_comment = false;
            }
            continue;
        }
        if in_string {
            let c = bytes[i] as char;
            out.push(c);
            i += 1;
            if c == '\\' && i < bytes.len() {
                out.push(bytes[i] as char);
                i += 1;
            } else if c == '"' {
                in_string = false;
            }
            continue;
        }
        if bytes[i] == b'"' {
            in_string = true;
            out.push('"');
            i += 1;
            continue;
        }
        if i + 1 < bytes.len() && bytes[i] == b'/' && bytes[i + 1] == b'/' {
            in_comment = true;
            out.push_str("//");
            i += 2;
            continue;
        }
        let rest = &source[i..];
        if let Some((from, to)) = replacements.iter().find(|(from, _)| rest.starts_with(from)) {
            out.push_str(to);
            i += from.len();
            continue;
        }
        let c = rest.chars().next().unwrap();
        out.push(c);
        i += c.len_utf8();
    }
    out
}

pub const STARTER: &str = r#"//! A complete Ax API service in one file.
module app;

// ax-api port 8080
// ax-api GET /health -> health
// ax-api GET /v1/items/{id} -> show_item
// ax-api POST /v1/items -> create_item

fn health(request: http.Request) -> http.Response =
    api.ok({ok: true});

fn show_item(request: http.Request, id: String) -> http.Response = api.ok(id);

fn create_item(request: http.Request) -> http.Response =
    api.created(request.body);
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_static_and_parameter_routes() {
        let (app, generated) = compile(STARTER).unwrap();
        assert_eq!(app.port, 8080);
        assert_eq!(app.routes.len(), 3);
        assert!(generated.contains("health(request)"));
        assert!(generated.contains("show_item(request, str.drop(request.path"));
        assert!(generated.contains("http.serve_handler(8080u16, __ax_api_dispatch)"));
        assert!(generated.contains("request.path == \"/openapi.json\""));
        assert!(generated.contains("openapi\\\":\\\"3.1.0"));
        assert!(!generated.contains("api.ok("));
    }

    #[test]
    fn generated_program_checks_and_lowers_with_core_ax() {
        let (_, generated) = compile(STARTER).unwrap();
        let mut session = ax::driver::Session::new();
        let file = session.parse("generated.ax", &generated).unwrap();
        let checked = session.check(&file);
        assert!(
            !checked.diags.iter().any(|diag| diag.is_error()),
            "{}",
            ax::driver::render_diags(&session.sm, &session.intern, &checked.diags)
        );
        let c = ax::codegen::emit_c(&session.intern, &checked).unwrap();
        assert!(c.contains("ax_rt_http_serve_handler"));
        assert!(!c.contains("ax_rt_api_"));
    }

    #[test]
    fn rejects_duplicate_route_shapes() {
        let source =
            "module t;\n// ax-api GET /items/{id} -> a\n// ax-api GET /items/{slug} -> b\n";
        assert!(compile(source).unwrap_err().contains("duplicate route"));
    }

    #[test]
    fn does_not_rewrite_strings_or_directives() {
        let source = "module t;\n// ax-api GET / -> root\nfn root(r: http.Request) -> http.Response = api.ok(\"api.ok(\");\n";
        let (_, generated) = compile(source).unwrap();
        assert!(generated.contains("http.response(200u16, \"api.ok(\")"));
    }

    #[test]
    fn rewrites_structured_response_literals() {
        let source = r#"module t;
// ax-api GET / -> root
fn root(r: http.Request) -> http.Response =
    api.ok([{id: 1, name: "first", active: true}]);
"#;
        let (_, generated) = compile(source).unwrap();
        assert!(generated.contains(
            r#"http.response(200u16, "[{\"id\":1,\"name\":\"first\",\"active\":true}]")"#
        ));
        let mut session = ax::driver::Session::new();
        let file = session.parse("generated.ax", &generated).unwrap();
        let checked = session.check(&file);
        assert!(
            !checked.diags.iter().any(|diagnostic| diagnostic.is_error()),
            "{}",
            ax::driver::render_diags(&session.sm, &session.intern, &checked.diags)
        );
    }

    #[test]
    fn rewrites_structured_literal_in_status_response() {
        let source = r#"module t;
// ax-api GET / -> root
fn root(r: http.Request) -> http.Response = api.json(202u16, {status: "queued"});
"#;
        let (_, generated) = compile(source).unwrap();
        assert!(generated.contains(r#"http.response(202u16, "{\"status\":\"queued\"}")"#));
    }

    #[test]
    fn supports_nested_wildcard_extraction_and_server_config() {
        let source = r#"module t;
// ax-api port 9090
// ax-api body_limit 2048
// ax-api timeout_ms 2500
// ax-api cors https://example.test
// ax-api auth Authorization=Bearer%20token
// ax-api session sid
// ax-api GET /users/{user}/posts/{post_id} -> show query=expand header=X-Trace
// ax-api GET /assets/*path -> asset
fn show(r: http.Request, user: String, post_id: String, expand: String, trace: String) -> http.Response = api.ok(user);
fn asset(r: http.Request, path: String) -> http.Response = api.ok(path);
"#;
        let (_, generated) = compile(source).unwrap();
        assert!(generated.contains("http.path_match(request.path, \"/users/{}/posts/{}\")"));
        assert!(generated.contains("http.path_param(request.path, \"/users/{}/posts/{}\", 0u16)"));
        assert!(generated.contains("http.query_param(request.query, \"expand\")"));
        assert!(generated.contains("http.header(request.headers, \"X-Trace\")"));
        assert!(generated.contains("http.serve_handler_config(9090u16"));
        assert!(generated.contains("request.path, \"/assets/*\""));
        let mut session = ax::driver::Session::new();
        let file = session.parse("generated.ax", &generated).unwrap();
        let checked = session.check(&file);
        assert!(
            !checked.diags.iter().any(|diagnostic| diagnostic.is_error()),
            "{}",
            ax::driver::render_diags(&session.sm, &session.intern, &checked.diags)
        );
    }

    #[test]
    fn supports_typed_json_body_routes() {
        let source = r#"module t;
// ax-api POST /items -> create body=Item
type Item = {name: String, count: u64};
fn create(r: http.Request, item: Item) -> http.Response = api.ok(item.name);
"#;
        let (_, generated) = compile(source).unwrap();
        assert!(generated.contains("json.decode(test.alloc, request.body)"));
        let mut session = ax::driver::Session::new();
        let file = session.parse("generated.ax", &generated).unwrap();
        let checked = session.check(&file);
        assert!(
            !checked.diags.iter().any(|diagnostic| diagnostic.is_error()),
            "{}",
            ax::driver::render_diags(&session.sm, &session.intern, &checked.diags)
        );
    }
}
